### ISSUE TITLE
multi-row: scroll should follow the active tab

### ISSUE THREAD

**Issue by jtagcat** [MrOtherGuy/firefox-csshacks#101]

**Comment by MrOtherGuy** [comment]
What do you mean by that? Well, I fear it might be impossible to achieve regardless of what you meant since css gives you no way to control how the tab rows are scrolled.

**Comment by jtagcat** [comment]
Indeed.

Well if I have 3 rows visible, and 12 rows open, it's bothersome (and difficult due to it only wanting to be on the first or last rows) to scroll all the time.

**Comment by MrOtherGuy** [comment]
Are you saying that there isn't any "scroll-stops" between last and first row? Like, if you are at the top and then use scrollwheel once, the scrollbox jump all the way to the end?

On my system one turn of a scroll wheel scrolls little less than three rows. It would seem to be affected by same scrolling behavior that is used for content pages. So, prefs like `mousewheel.system_scroll_override_on_root_content.vertical.factor` affect how much is scrolled.

But! It turns out that you can use css scroll-snapping to make scroll amount more "exact". I've just pushed a patch that on Firefox87 makes the rows scroll exactly 3 rows. With Fx89 and proton it's exactly 2 rows. The difference is probably that the scroll distance is closer to 2 than 3 full rows with proton.

So, while that isn't a complete win it's at least progress.

**Comment by jtagcat** [comment]
Indeed, it's a major win. Following the tab is thus a more minor issue.

**Comment by MrOtherGuy** [comment]
That scroll-snap feature should now be in multi-row tabs style. It should have been there yesterday, but I had some technical difficulties on my end. So please test and see how it works for you.

**Comment by jtagcat** [comment]
I've used it for a bit now, I'd say it still results in overshooting (it doesn't move instantly, takes some 'force'/momentum to get moving, and then you already have too much scrolling momentum.  
Without, it still overshoots, so a tiny bit better I guess?

**Comment by MrOtherGuy** [comment]
I honestly have no clue what causes such differences in scrolling between us. Anyway, to make scrolling instant, you would need to disable smooth scrolling which of course would also disable smooth scrolling on web pages.

**Comment by jtagcat** [comment]
Aight

Closing for now?
