### ISSUE TITLE
Tabs on bottom, menu bar in wrong place.

### ISSUE THREAD

**Issue by ForisTale** [MrOtherGuy/firefox-csshacks#105]
Hi. After use of tabs_on_bottom.css menu bar is in the wrong place, hope this screen explain everything.
![screen](https://user-images.githubusercontent.com/45861985/117879371-cedb7d80-b29e-11eb-8230-92cc3838aeaf.png)

**Comment by MrOtherGuy** [comment]
[tabs_on_bottom_menubar_on_top_patch.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/tabs_on_bottom_menubar_on_top_patch.css) which is mentioned in the main file exists for the exact purpose of moving menubar on top. It's not included in the tabs_on_bottom.css for a rather complicated reason and although I would like to combine them its just not possible.

So, providing a separate patch file is fine I think, since not many folks have menubar enabled in the first place.

**Comment by ForisTale** [comment]
Thank you, now it's work perfectly!
