### ISSUE TITLE
Using Both navbar_below_content.css and hide_tabs_toolbar.css

### ISSUE THREAD

**Issue by freelyskycloud** [MrOtherGuy/firefox-csshacks#125]
When using `navbar_below_content.css` and `hide_tabs_toolbar.css` together, the navbar does go to the bottom but the tabs bar doesn't go away. My question is if it is possible to have both enabled at the same time.

userChrome.css:
```
@import url(chrome/navbar_below_content.css);
@import url(chrome/hide_tabs_toolbar.css);

```
Note the tabs bar above my bookmarks bar.
![2021-07-19-131243_1279x148_scrot](https://user-images.githubusercontent.com/53827363/126200608-a6126144-d1fb-434d-9b0d-583b6bc5aed0.png)

**Comment by MrOtherGuy** [comment]
Well, this kinda depends on how you want or don't want window controls to show. They are normally inside tabs toolbar so if you hide it, then you don't have window controls - unless you have either menubar or native titlebar enabled.

But if you *do* have either native titlebar or menubar enabled then instead of hide_tabs_toolbar.css you can use just this: `#TabsToolbar{ visibility: collapse }`

Then if you *don't have either enabled* AND you don't want window controls to appear at all then you could use something like this:

    :root{ --tab-block-margin: var(--proton-tab-block-margin) }
    #TabsToolbar{ visibility: hidden }
    #titlebar{ margin-bottom: calc(0px - 2 * var(--tab-block-margin) - var(--tab-min-height)) }

And lastly if you instead want window controls to appear next to bookmarks toolbar then you could use hide_tabs_toolbar.css but add this "patch" after it:

    #nav-bar.browser-toolbar{ margin-top: 0 }
    :root:not([inFullscreen]) #PersonalToolbar{
      margin-top: calc(0px - var(--uc-toolbar-height)); 
      padding-right: 154px !important;
      min-height: 31px !important;
    }
    :root{ --uc-toolbar-height: 31px !important; }

Or, for the window-controls in bookmarks toolbar you have also another option. Use the code for the second behavior (so no real window controls) but get extensions that provide window control buttons and just place them to bookmarks toolbar. I actually wrote such extensions just yesterday.

* [minimize](https://addons.mozilla.org/en-US/firefox/addon/movable-window-minimize-button/)
* [maximize](https://addons.mozilla.org/en-US/firefox/addon/movable-window-maximize-button/)
* [close](https://addons.mozilla.org/en-US/firefox/addon/movable-window-close-button/)

But it appears the minimize button hasn't passed review yet, but it will probably happen soon-ish.

**Comment by freelyskycloud** [comment]
Thanks, those helped me very much. I have a separate issue with `navbar_below_content.css`. Not sure if this should be in a different issue, but when using `navbar_below_content.css` clicking on an extension in the navbar doesn't bring up a popup.

Example: when uBlock Origin is placed in the navbar and you click on it nothing happens.

**Comment by MrOtherGuy** [comment]
Yes, I know they don't work. Actually I thought I had added a note to the style that they don't work and trying to open them might even crash Firefox, but seem I have not.

I can't fix that unfortunately. A workaround though is to move the extension buttons into the overflow-menu. They will work inside that.

**Comment by freelyskycloud** [comment]
That's a shame. Thanks for the help anyways.
