### ISSUE TITLE
autohide_bookmarks_toolbar.css::transparent bg problem

### ISSUE THREAD

**Issue by Sadi58** [MrOtherGuy/firefox-csshacks#130]
In Firefox 90 (Linux) I've found that this works instead:

```
#PersonalToolbar {
visibility: collapse !important;
}
#navigator-toolbox:hover > #PersonalToolbar {
visibility: visible !important;
}
```

**Comment by MrOtherGuy** [comment]
Hmm, I think I know what you mean by transparent background problem - it happens if your theme uses a toolbar background that is not completely opaque. The CSS you posted certainly works to get around *that specific issue* but the behavior is quite different.

I have added a workaround for the style in 04e15ab and 81a94ba for this. It's kinda wordy, but should allow the bookmarks toolbar to look like it belongs to other toolbars even with themes with background-images and non-opaque toolbars.

**Comment by Sadi58** [comment]
OK. Thanks.
