### ISSUE TITLE
Some problems with `autohide_tabstoolbar.css` and `tabs_on_bottom.css`

### ISSUE THREAD

**Issue by QuantumStatement** [MrOtherGuy/firefox-csshacks#134]
1. System buttons aren't shown when tabs are hidden
![nobuttons](https://user-images.githubusercontent.com/35406698/129435866-19971db8-9c79-45bc-83e8-41d14862b036.png)
2. Tabs toolbar is transparent
![transparent-tabstoolbar](https://user-images.githubusercontent.com/35406698/129435868-95e960fc-6669-4380-a9c2-31da4da3af2c.png)
3. Tabs toolbar popups too early and thus blocks access to site header elements

**Comment by MrOtherGuy** [comment]
Hmm, alright I can patch up tabs_on_bottom.css such that the window controls show when used with autohide_tabstoolbar.css

But I'm not sure why tabs toolbar wouldn't have any background on your setup. Neither of the styles modify it's background so it should just be whatever your theme sets it to. So like, I guess it's possible that your theme specifically makes tabs toolbar transparent, but I can't see why it would do that.

You could override the color easily by adding: `#TabsToolbar{ background: red !important; }`, but I would like to understand under which circumstances the background would be transparent in the first place. Perhaps with Win7 and Win8 that could happen?

> Tabs toolbar popups too early and thus blocks access to site header elements

I'm not sure what you mean by this but I guess it would be fixed with the same patch that makes window controls visible even when tabs toolbar isn't hovered.

Try the updated version of tabs_on_bottom.css

**Comment by QuantumStatement** [comment]
1. Now it's working, thanks
2. > Perhaps with Win7 and Win8 that could happen?

No, it's Win10. I'm using Firefox 91 with System theme
![systemtheme](https://user-images.githubusercontent.com/35406698/129444084-c82ff68d-8004-4718-8e73-b5243a5ad9bf.png)
But if I set another theme (Light, Dark or Alpenglow for example) then tabs background is shown properly

3. I mean this:
Where cursor is pointing when tabs are shown
![cursor1](https://user-images.githubusercontent.com/35406698/129444244-dad068fd-cb04-425c-a1f1-e37c7c636087.png)
Where cursor should be
![cursor2](https://user-images.githubusercontent.com/35406698/129444246-b625073f-902d-4410-8111-b4afc2bc528d.png)

**Comment by MrOtherGuy** [comment]
Okay, yeah, I can reproduce with system theme when it is the light variant.

Also, thanks for pointing out the hovering thing. Both should be fixed with the latest changes to both styles, but please confirm.

**Comment by QuantumStatement** [comment]
Now it works properly. Thanks!
