### ISSUE TITLE
Non-active selected tabs not highlighted with non_floating_sharp_tabs

### ISSUE THREAD

**Issue by Dunedan** [MrOtherGuy/firefox-csshacks#150]
When using `non_floating_sharp_tabs` with a Firefox version which use the Proton theme (Firefox 93 in this case) when selecting multiple tabs the selection isn't visible, making it impossible to see if a non-active tab is selected or not.

In one of the following screenshots only the active tab is selected, in the other one the second tab is selected as well. As you see, you can't see the difference.

![tabs-selected1](https://user-images.githubusercontent.com/1735355/136702029-de039851-9fdf-4ea7-afac-74c72e3a5de6.png)
![tabs-selected2](https://user-images.githubusercontent.com/1735355/136702030-c2d86f13-2b92-4d29-8772-6a55d8cb6751.png)

Without `non_floating_sharp_tabs` all selected tabs get the same border as the active tab, making it clear which tabs are selected (slightly off-topic, but interestingly that makes it impossible to distinguish between the active tab and non-active selected tabs). With Photon that was much better. I believe selected tabs just got the same darker background color as hovered tabs making it possible to distinguish between the active tab and inactive selected and unselected tabs. I suggest to add that same behavior to `non_floating_sharp_tabs` as well.

**Comment by MrOtherGuy** [comment]
> I have a question related to this update, you added a note to set layout.css.color-mix.enabled to true. i've tried it both true and false and have noticed absolutely no visual differences. is it supposed to do something readily apparent?

I shoyld have added that note back when I created the style but forgot. But yes, it should an effect. In the past months at least, without the pref the border around tab and between tabs toolbar and nav-bar was not necessarily using correct colors, because those colors were (I think depending on your theme) computed using color-mix which was not supported without that pref except for infernal styles. 

I suppose it's possible that it now works also in user stylesheets. But anyway, I think it's possible that you don't see any effect when using certain themes.
