### ISSUE TITLE
How to theme win7 window control buttons(close, restore/maximize, minimize)

### ISSUE THREAD

**Issue by youring** [MrOtherGuy/firefox-csshacks#174]
Hello,
I'm still using windows 7 and fall in love with the [Dark Space](https://addons.mozilla.org/en-US/firefox/addon/nicothin-space/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=rating) theme recently.
But the control buttons is still not themed like below
![win7controlbuttons](https://user-images.githubusercontent.com/4132418/154188859-d7e2acc8-58a6-4cde-b684-6c2136cf57f9.jpg)
Is it possible to theme it using csshacks? Or some addons available?
If not possible, can we just simply hide these three ugly buttons while in dark mode?
Thank you all for reading and suggestions.

**Comment by MrOtherGuy** [comment]
I can't help you too much since I have no access to Win7 machine I could test. The only thing I remember from years ago was that you would need to add: `#main-window{ -moz-appearance: none !important }` which among other things removes that button box. But I think there was some other thing you need to do as well, and chances are that things have changed since then considerably.

So yeah, I can't really help you with this. Sorry.

**Comment by MrOtherGuy** [comment]
I don't think you can do anything else to the light theme except to just draw light background over them. Such as with `#titlebar{ background: white !important }`
