### ISSUE TITLE
window_control_force_linux_system_style.css is not working.

### ISSUE THREAD

**Issue by hrqmonteiro** [MrOtherGuy/firefox-csshacks#199]
Applied that and my titlebar controls are still not styled by the gtk theme.

![Screenshot from 2022-07-31 23-21-53](https://user-images.githubusercontent.com/17055027/182060098-3185ec4b-d222-4dc0-ace8-b0f26fb2cc6c.png)

**Comment by MrOtherGuy** [comment]
Hmm, that style seems to work fine on my system. And the icons in your screenshot also look *more* like the system icons rather than what Firefox would draw without that style.

Perhaps what's going on is that Firefox actually does use system icons, but the rest of your shell uses some custom window control buttons. I kinda doubt there anything you can do here except to manually apply some styling to window control buttons according to match what you want them to look like.
