### ISSUE TITLE
shrinking_pinned_tabs + mutli-row_tabs flicker glitch

### ISSUE THREAD

**Issue by sonofevil** [MrOtherGuy/firefox-csshacks#202]
There's an awkward situation when you have both installed, where when pinned tabs are right on the verge of overflowing, and you open an unpinned tab, it starts 'flickering' back and forth between the normal pinned tab width and the shrunk one.

This is presumably because the arrow-scrollbox overflow happens earlier than the multi-line-break.

For me personally the problem is solved by simply removing `:not([overflowing])` from shrinking_pinned_tabs, but users without multi-row_tabs may want a different solution.

**Comment by MrOtherGuy** [comment]
Sorry, I don't really understand what you mean. If you use multi-row_tabs.css then the tabs won't overflow at all - or at least they shouldn't. So, I can't really figure out what you mean by "right on the verge of overflowing" - maybe a video clip would help?

**Comment by sonofevil** [comment]
Whatever `:not([overflowing])` refers to.

**Comment by MrOtherGuy** [comment]
I've been trying to reproduce this but I'm not sure what exactly I'm looking for. When you say " it starts 'flickering' back and forth", do you mean it will start to continuously flicker without end (until you perhaps open yet another tab or change window width or something)? Or is it just brief "flicker" during tab opening animation?

I definitely can't seem to reproduce the former, and if it's just one flick during opening then it's unclear how that should be fixed because during the animation all tabs indeed do fit single row (since the pinned tabs make space for them by collapsing a bit). You would somehow need to be able to tell the layout that if the new tab would "eventually" (i.e. after the animation finishes) cause an second row to appear, then in that case pinned tabs should not shrink. That's not really possible and workarounds may be more complicated than you would think.

**Comment by sonofevil** [comment]
It flickers endlessly, slowing down the browser in the process, but stops when you open or close another tab.

Since I have a workaround, no one else has reproduced it yet and there is no obvious universal fix (I've been trying to find one myself to no avail, I'm actually not even sure what exactly causes it, the slowdown makes it hard to find the relevant properties), it's by no means a high priority issue. I just thought I should mention it.

**Comment by sonofevil** [comment]
Basically, it sometimes does this, and I'm not sure why: 
https://cdn.discordapp.com/attachments/235456282998472704/1046026828223086612/simplescreenrecorder-2022-11-26_12.33.16.mkv

It stops when I unpin one tab, and doesn't necessarily start again when I re-pin it. It's kinda random.

**Comment by sonofevil** [comment]
Any ideas for how to debug this? Once it starts, using dev tools becomes near impossible due to app slowdown, so I can't check which rule keeps changing. 

I would guess it is some rule that applies conditionally on overflow, but then once it applies changes the layout such that the browser thinks it's no longer overflowing etc. But searching the browser css files for "overflow" didn't yield anything useful.

**Comment by MrOtherGuy** [comment]
The best I can think of is to use devtools to set a breakpoint [here](https://searchfox.org/mozilla-central/rev/b77aed8146805795350e7e127869c395ab70efdf/browser/base/content/tabbrowser-tabs.js#1122) before the issue seems to manifest. So when it does happen the front-end code should stop. At that point, I think, the layout should be in "overflowing" mode, and you can maybe try to fond out what layout rules get applied to try to figure out some clues.

**Comment by sonofevil** [comment]
It hasn't happened since I changed the behavior of the new tab button (no hiding on overflow), leading me to believe it was caused by that after all.

**Comment by sonofevil** [comment]
Nah, it was "fixed" by the breakpoint. Duh!

Anyway, this apparently happens because of these two rules in browser.css:


```
#tabbrowser-tabs[positionpinnedtabs] > #tabbrowser-arrowscrollbox::part(scrollbox) {
    padding-inline: var(--tab-shadow-max-size);
}

#tabbrowser-arrowscrollbox::part(scrollbox) {
    overflow-y: auto;
}
```

Disabling either will fix it.

**Comment by MrOtherGuy** [comment]
> #tabbrowser-arrowscrollbox::part(scrollbox) {
>    overflow-y: auto;
> }


For the record, multi-row_tabs.css doesn't have a rule like that - it wouldn't have any effect anyway since `::part()` selector doesn't match anything in userChome.css. Although [line 38](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_tabs.css#L38) might cause the same thing.

**Comment by sonofevil** [comment]
Oh right, I copypasted the wrong selector, sorry.

Fix: https://github.com/MrOtherGuy/firefox-csshacks/pull/248
