### ISSUE TITLE
Collapsing tab bar causes  ui to overlap with itself.

### ISSUE THREAD

**Issue by fislysandi** [MrOtherGuy/firefox-csshacks#206]
![firefox_Wb1sIifgSj](https://user-images.githubusercontent.com/45166203/191556423-43395beb-3b99-4a69-b779-ce5ed153186f.png)

i just want to hide the tab section and i get this why is this so difficult?

**Comment by fislysandi** [comment]
the ui just overlaps on top of each other

**Comment by MrOtherGuy** [comment]
You mean window controls overlapping the toolbar.

Sounds like you did not apply [the supporting style](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/window_control_placeholder_support.css).

**Comment by fislysandi** [comment]
![WindowsTerminal_bE7gy9edlX](https://user-images.githubusercontent.com/45166203/191559473-889aae5d-4410-4f2e-8b86-f1920f6c0f32.png)


![firefox_pKSLTQJ9sw](https://user-images.githubusercontent.com/45166203/191559526-72769efe-8d65-4d5f-bfd0-9294af976621.png)

:(

**Comment by MrOtherGuy** [comment]
That doesn't look right. The `chrome` folder should also include `userChrome.css` because that (along with userContent.css which only affects content documents like web content) is the only file Firefox knows about.

If you save those styles as separate files (which is a good thing to do), then your userChrome.css should contain this at the very top of the file:

```css
@import url("window_control_placeholder_support.css");
@import url("tabs_on_bottom.css");
```

Another option is to just put contents of both files straight into `userChrome.css` but as separate files they should be easier to manage and update when needed etc. so I would recommend that.

**Comment by fislysandi** [comment]
sec ill try to figure this out.

**Comment by fislysandi** [comment]
FUCK YEAH WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 
![firefox_Y9h12jOX25](https://user-images.githubusercontent.com/45166203/191563988-2bbfccd5-b559-4675-8735-addc47d73293.png)

**Comment by fislysandi** [comment]
i just use the tree tab addon and the general tab bar takes too much space for my liking so THANK YOU SO MUCH FOR MAKING THIS!

**Comment by MrOtherGuy** [comment]
No problem. I'll close this issue since it seems to be resolved.
