### ISSUE TITLE
nav-bar and multirow tabs below content - broken on FF 107

### ISSUE THREAD

**Issue by spoooyders** [MrOtherGuy/firefox-csshacks#226]
Hi.

I am using `toolbars_below_content.css` + `multi-row_tabs.css` on FF 107 (Linux).
And it started to look weird after latest FF update. I didn't update my userChrome for a while. I tried to use latest versions of `toolbars_below_content.css` + `multi-row_tabs.css` and it is still broken...

I have 3 tab rows and looks like empty tab rows are being always displayed now and eating display space:

![2022-11-17-031230_2551x1356_scrot](https://user-images.githubusercontent.com/118410979/202337454-a2e967c4-3900-47b8-9330-ea6b0ad11cc9.png)

Could you please help.
Thanks.

**Comment by killerz298** [comment]
I'm seeing the same here with 107 64-bit on windows 10.

**Comment by killerz298** [comment]
Good here as well. I'll check back to see if anyone reported anything breaking.

**Comment by MrOtherGuy** [comment]
Good to hear that setting that pref works without major trouble.

I think the best I could do would be to add a comment to multi-row_tabs.css to instruct the user to set that pref for 107 cycle.

**Comment by Cuervino** [comment]
Thanks, worked for me also! (https://github.com/MrOtherGuy/firefox-csshacks/issues/215#issuecomment-1283490393)

**Comment by loby66** [comment]
a litlle pb btw, the pref truncates the search bar panel (only one row displayed)
https://i.imgur.com/kJxceng.jpg

**Comment by SanderBouwhuis** [comment]
I had the same problem, and https://github.com/MrOtherGuy/firefox-csshacks/issues/215#issuecomment-1283490393 worked for me to:
1. Go to about:config
2. set **layout.css.moz-box-flexbox-emulation.enabled** to true

**Comment by shlomich** [comment]
Maybe we can add it to the multirow file so people know from X version it must be enabled aswell.

**Comment by dmovztoq** [comment]
Same here when it normally updated to FF 107 on OpenSUSE Tumbleweed KDE yesterday, setting Set `layout.css.moz-box-flexbox-emulation.enabled` to true seemed to fix both bookmarks and tabs, there was also an extra empty row in the bookmark bar. Haven't checked Windows 10 yet (but I don't update FF so often there precisely because of things like this)

**Comment by MrOtherGuy** [comment]
Thanks for testing.

I've checked multi-row_tabs.css, multi-row_tabs_below_content.css and multi-row_bookmarks.css with Nightly 108 on both Win10 and Linux (Fedora 36) and they seem to work fine as far as I can tell. That is with the mentioned pref `layout.css.moz-box-flexbox-emulation.enabled` is set to `false` as well as when it is set to `true`

**Comment by SanderBouwhuis** [comment]
@MrOtherGuy
So, you are saying the setting itself is only causing a side-effect which accidentally makes it work for some people (including me)?
Would it help you if I were to give you my settings to see whether you can reproduce it?

**Comment by MrOtherGuy** [comment]
No.
The setting causes different algorithm to be used for rendering tabs toolbar in Firefox 107. I'm not 100% sure, but I believe that the same algorithm is used in Firefox 108 and later whether that pref is set or not.

The pref is required in 107 because some parts of the layout algorithm (that don't matter for normal layout) have already been reworked and the only way to work around it would be to make 107 also use flexbox-emulation for toolbars.

That's how I understand the situation anyway.

> Would it help you if I were to give you my settings to see whether you can reproduce it?

What is the problem that you are still experiencing?

**Comment by SanderBouwhuis** [comment]
@MrOtherGuy
After setting the `layout.css.moz-box-flexbox-emulation.enabled` preference, it works great for me. I just thought you didn't understand what failed because for you it doesn't matter whether the preference is true or false.

**Comment by Argument7** [comment]
With last patch, all work fine. Thank you!
