### ISSUE TITLE
navbar_below_content bugs the "allow site to install an add-on" pop-up

### ISSUE THREAD

**Issue by LupSpie** [MrOtherGuy/firefox-csshacks#249]
When using `navbar_below_content.css`, the pop-up asking to allow the site to install add-ons exceeds the boundaries of the window.

---

![Issue](https://user-images.githubusercontent.com/49603837/213897681-0259150b-6d64-4464-a4f0-3697780fa794.png)

**Comment by MrOtherGuy** [comment]
Sadly I can't really fix this.

The behavior of that panel is such that if it doesn't fit to same **screen** as the Firefox window then Firefox will flip it to open its bottom attached to the anchor point (extension button in this case). But since it does fit into the screen then Firefox will do this and let it exceed the window bounds.

You can do something like: `#notification-popup[side="top"]{ margin-top: -134px !important; }` but this is a general panel that is used for all kinds of purposes and it is not necessarily anchored to the extension button. So if you apply that margin-top hack, then the same margin will apply to all notifications that use that general panel, and the panel may have different height in each scenario so that `-134px` isn't even suitable for all scenarios.

Thus, I think that the current behavior is the least broken option here. It's annoying that it exceeds the window, but it's usable at least.

**Comment by LupSpie** [comment]
Oh well, bummer that it can't really be fixed, but I understand it 🫤. I'll be using the hack you provided as it seems to work for the most part. Anyways, thank you for your time!

btw should this issue be closed?
