### ISSUE TITLE
how to make autohide_sidebar.css support drag to resize sidebar width?

### ISSUE THREAD

**Issue by u-Sir** [MrOtherGuy/firefox-csshacks#268]
Now I use this to make the sidebar unlimited in width
```
#sidebar-box {
  max-width: none !important;
}
```
how to make autohide_sidebar.css support drag to resize sidebar width?

**Comment by MrOtherGuy** [comment]
That won't work, at least I don't think there's any way to make it work. If there is some way (which I don't think there is) then it would only affect the reserved width it hidden state, because the drag-handle essentially affects how much space the sidebar takes from the web-content area. And that style makes it so that the shown sidebar state doesn't change the width available for web-content (otherwise hovering the sidebar would move the content web content area).

**Comment by u-Sir** [comment]
> That won't work, at least I don't think there's any way to make it work. If there is some way (which I don't think there is) then it would only affect the reserved width it hidden state, because the drag-handle essentially affects how much space the sidebar takes from the web-content area. And that style makes it so that the shown sidebar state doesn't change the width available for web-content (otherwise hovering the sidebar would move the content web content area).

thanks for your quick response. By the way, is there any way to scale/zoom the sidebar? Currently, I am using 'Open in Sidebar', a Firefox addon, but the scale on the sidebar never change automatically on the second screen.

**Comment by MrOtherGuy** [comment]
I think the only way to have such zoom functionality would be for that "Open in Sidebar" extension to add such a feature. You should ask the extension author about that.

I'll close this issue since there's not really anything we can do here.
