### ISSUE TITLE
Bug on Ubuntu 23.04

### ISSUE THREAD

**Issue by xmha97** [MrOtherGuy/firefox-csshacks#274]
Please improve "window_control_placeholder_support.css"
There is a bug on Ubuntu 23.04

![Screenshot from 2023-04-26 04-59-27](https://user-images.githubusercontent.com/23485114/234442855-d95d9d4f-f47a-4b4c-9f10-791c8ea7d1aa.png)

Thanks 🙏

**Comment by MrOtherGuy** [comment]
I hope this is now fixed with https://github.com/MrOtherGuy/firefox-csshacks/commit/0b814166575ee45917337fc743895710af6b6f1e

I don't have Ubuntu system to test with but I was able to find a theme with which I could confirm this behavior on my Fedora system. With the above patch it all seems to work fine now.

**Comment by xmha97** [comment]
Now It working fine.
Thanks 🙏

**Comment by MrOtherGuy** [comment]
Alright, thanks for reporting!
