### ISSUE TITLE
@import url - doesn't work WTF, bro❓ 😣

### ISSUE THREAD

**Issue by rediffusion** [MrOtherGuy/firefox-csshacks#276]
Hi, Y'all! 👋
 Why the line like this so `@import url(hacks/autohide_navigation_button.css);` doesn't woking❓
Files are [here](https://files.fm/f/f27bj6rjx).

Thank you for your time!

**Comment by MrOtherGuy** [comment]
The files you linked seem to work just fine. But you should note that line comments (start with  `//`) are not supported in CSS. In this example it doesn't matter because you don't have any other CSS after that but if you would have then that would be ignored.

Also note that `@import` statements all need to be at the top of the file, otherwise they will be ignored.

**Comment by rediffusion** [comment]
@MrOtherGuy 
 You have made my day!
Many thanks!
