### ISSUE TITLE
hide_tabs_scrollbuttons: spacer position is now wrong

### ISSUE THREAD

**Issue by Dupond** [MrOtherGuy/firefox-csshacks#278]
Hello!
Since [the last commit](https://github.com/MrOtherGuy/firefox-csshacks/commit/0ff12e01fe18bc86ca68291c88c6dcf027cb9d83) the indicator appears on the middle of the first (or last) tab, whereas it should appear in front of the first tab or at the end of the last tab.

Is there a way to place it where it should be?

Please note that I modify the appearance of the spacer using the following code (that you gave once on the FirefoxCSS subreddit):

```
spacer[part="overflow-start-indicator"], spacer[part="overflow-end-indicator"] {
    z-index: 1;
    background: linear-gradient(color-mix(in srgb, currentColor 20%, transparent), color-mix(in srgb, currentColor 20%, transparent)) !important;
    background-size: 1px 100% !important;
    background-position-x: 0% !important;
    background-repeat: no-repeat !important;
    border-color: transparent !important;
}
```

Thank you very much for your help!

**Comment by MrOtherGuy** [comment]
I can't seem to reproduce this issue with or without that additional snippet you posted. I tried both Firefox 112 and Nightly 114 on Windows.

Please try without any additional styles other than those. Even better, it would be nice to know if you can reproduce the issue with ONLY hide_tabs_scrollbuttons.css.

**Comment by Dupond** [comment]
I forgot to mention that I use Firefox 112.0.2 with Linux.

So I've done some more tests:

- the issue can be reproduced with hide_tabs_scrollbuttons.css only;
- since I use Firefox 112, I have removed the following lines:

```
-moz-box-ordinal-group: 0; /* Fx < 112 compatibility */

...

-moz-box-ordinal-group: 2; /* Fx < 112 compatibility */
```

- BUT I've found that if I add them back, then the indicator is correctly placed... But shouldn't I remove them with Firefox 112.0.2?

**Comment by MrOtherGuy** [comment]
Oh I see the problem. Yes, the change for which I added them was initially in Firefox 112 but it was pushed back to Firefox 113. So really those should just say "Fx < 113 compatibility". Regardless, just leave them be, my intention was not that anyone would remove those rules, layout should work correctly both in Firefox 112 and 113 and 114 with those rules set (they just won't have any effect in 113 and 114). The comment is simply there so that I can quickly scan through all the files when I will remove those outdated rules - which will be after next ESR releases since ESR 102 needs those old rules.

**Comment by Dupond** [comment]
Oh OK. Thank you for the explanation.

I had deleted those lines because your commit says:

> A lot of style rules are marked as "Fx < 112 compatibility" rules and those can be removed when 112 hits release.

Thank you for your help!
