### ISSUE TITLE
Autohide_toolbox.css — Compatiability with Firefox Onebar

### ISSUE THREAD

**Issue by extremelyonline** [MrOtherGuy/firefox-csshacks#295]
Hi, great repo! I was wondering if you may shed some light on a problem with [autohide_toolbox.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_menubar.css): I am trying to get it to work alongside the [Firefox Onebar](https://codeberg.org/Freeplay/Firefox-Onebar) userChrome which put everything in a single bar.

The problem is that it uses `display: flex` under `#navigator-toolbox`. Is there a way to modify Autohide_toolbox.css and make it compatiable? Sorry if this is out of scope. Thank you.

**Comment by MrOtherGuy** [comment]
I assume you are really talking about `autohide_toolbox.css` since that's what you have written - the link you posted leads to `autohide_menubar.css`

I can't say what kind of things you would need to do to make it work for large external style like Onebar. But, for much the same purpose you could insted try [navbar_tabs_oneliner_tabs_on_left.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/navbar_tabs_oneliner_tabs_on_left.css) which should work mostly fine with `autohide_toolbox.css`. Just remember to get [window_control_placeholder_support.css](https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/window_control_placeholder_support.css) as well (a requirement for navbar_tabs_oneliner_tabs_on_left.css), and change the toolbox rotation value [on line 11](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_toolbox.css#L11) to something a bit smaller like maybe `75deg` because that depends on how tall the toolbox is as a whole.
