### ISSUE TITLE
Tabs on Bottom broken in V117 (again...)

### ISSUE THREAD

**Issue by GrizzlyAK** [MrOtherGuy/firefox-csshacks#302]
I just noticed that when you have a bunch of tabs open, the last tab is partly off screen and does not display a close "X" when selected. Although, once it did, depending on size (I had about 40 tabs). Very weird behavior, but something in V117 broke the current userChrome.css (Mine is dated 5/18/23, but there is no version info in the file that I could find. I got it here).

When the userChrome is disabled and Tabs are on top, the X's work correctly on all tabs.  Hopefully, you'll be able to find a workaround (again) to save the millions of us who rely on you to work around Mozilla dev's stubborness.

**Comment by MrOtherGuy** [comment]
I just tried it with various combinations of menubar and/or titlebar being enabled/disabled and with _menubar_on_top_patch.css and as far as I can tell they all work fine in Firefox 117 as well as Nightly 119.

So, if there is a an issue then it might be OS dependent (I only tested Win10). But are you sure the problem is with tabs_on_bottom.css? Is it possible your userChrome.css has something *else* which is broken?

**Comment by GrizzlyAK** [comment]
Not sure what could have been happening. This was after a restart of FF after I had told it to install the update to 117 that this occurred. The last tab on the right did not show an X when selected, nor was there a ">" at the end that allowed you to scroll the tabs. However, I just checked again following your update here and following a reboot of my system (for other reasons), and the tabs appear to be working as expected now, to include the X and the > on the right. Sorry for the bother. I will let you know if I see this behavior again. I definitely wasn't imagining it. Cheers.
