### ISSUE TITLE
Issue with round_ui_items

### ISSUE THREAD

**Issue by AlienIdeology** [MrOtherGuy/firefox-csshacks#312]
There are two slight issues concerning the tabs bar when applying round_ui_items.css:
1. A space is created between the URL (navs bar? idk the terminologies) and the tabs bar.
This seems to be caused by the margin-top style on [line 35](https://github.com/MrOtherGuy/firefox-csshacks/blob/3b184df8c43bce96b95b072c398f4d067f467a82/chrome/round_ui_items.css#L35). 
Screenshot:
![Imgur](https://i.imgur.com/mZZEEBI.png)
2. Sometimes (I'm not sure what triggers it) the tab itself is rounded. This seems to be caused by the border-radius of tab background on [line 25](https://github.com/MrOtherGuy/firefox-csshacks/blob/3b184df8c43bce96b95b072c398f4d067f467a82/chrome/round_ui_items.css#L25).
![Imgur](https://imgur.com/gPWMMX9.png)

I've fixed it by commenting out the relevant code, but I'm not sure if that has introduced more bugs.

**Comment by AlienIdeology** [comment]
Forgot to mention, I'm on v118.0.2 of Firefox, and my OS is macOS Sonoma 14.0

**Comment by MrOtherGuy** [comment]
That extra empty space probably was added because the style was written originally for the old photon styling where tabs were "connected" to the toolbar below. Now with proton we shouldn't be adding that anymore. I'll fix that.

But it looks like you are using some other style as well to shape the tabs. That I can't do anything about - this style is supposed to make the tabs round as well, and that is incompatible with your current tab shaping rules whatever they are. I would think the to fix it for yourself you only need to remove that `.tab-background` selector from line 25 like you already mentioned.

**Comment by AlienIdeology** [comment]
I see.
Yeah, I'm using another style. I didn't realize that it's supposed to make the tab round, but that makes sense.
Thanks for maintaining this awesome project!
