### ISSUE TITLE
[Bug] Bookmarks rows are transparent after Firefox v.119

### ISSUE THREAD

**Issue by Elaws** [MrOtherGuy/firefox-csshacks#315]
# Problem description 

After Firefox v.119 update, bookmarks rows are transparent :

![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/52013479/498913a3-28c3-4483-b26a-7001fbd8027c)

# Context 

Content of `userChrome.css` :

```css
@import url(chrome/multi-row_bookmarks.css);
@import url(chrome/autohide_bookmarks_toolbar.css);
@import url(chrome/hide_tabs_toolbar.css);
@import url(chrome/window_control_placeholder_support.css);
```

Firefox : v.119
Just did a `git-pull` to get latest firefox-csshacks.

**Comment by MrOtherGuy** [comment]
This is really a bug on Firefox side - [see bug 1853524](https://bugzilla.mozilla.org/show_bug.cgi?id=1853524) 

Here the issue is triggered by autohide_bookmarks_toolbar.css and as far I know it only manifests on Firefox 119 (behavior is correct in Firefox 120, currently in beta) and only if you use default theme. If you use any other theme then this issue doesn't happen even in 119. 

So, I don't feel like trying to work around this for only Firefox 119 and only to support users using default theme.

Adding a workaround for just Firefox 119 and only for default theme is kinda annoying, but I suppose it's alright to do since it's not super complicated.

**Comment by Elaws** [comment]
Thank you, just `git pull`'d and it works like a charm.
