### ISSUE TITLE
A black bar appearing after bookmark toolbar disappears

### ISSUE THREAD

**Issue by SakuraHH** [MrOtherGuy/firefox-csshacks#32]
So I tried using your [CSS](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_bookmarks_toolbar.css) for automatically hiding the bookmark toolbar when not focused/hovering, but it is leaving behind a black [bar](https://imgur.com/a/iK0GyrZ).
As far as I know it should be working alright, but not with me for some reason, even with a clean userChrome file. Would you happen to have any more knowledge about the issue?

Thanks!

**Comment by MrOtherGuy** [comment]
If you don't have anything else in your userChrome.css file then this shouldn't happen.

However, if you do have set `privacy.resistFingerprinting.letterboxing` to true, then you might see something very similar where the style itself works exactly like it's supposed to but Firefox doesn't scale the web content to the full available space. In that case the bar is intended behavior. I don't really think that this is what you are experiencing but I cannot think anything else at the moment that would cause this (if indeed this happens without any other style)

**Comment by Ghis1964** [comment]
I'm having the same. What I need is the actual elements concerning these bars (each tool/top/bookmark/etc) Then, I'd be (hopefully) able to figure things by myself. I don't how to use the inspector to do this. The old firebug was great for that. But this firefox inspector keeps loosing the element as soon as I move the moose elsewhere (pissing me off each time)

Back to that "black space", mine is transparent because of windows7 ui. 
All I've been able to do is reduce its size(height) to 8 or 9 pixels. Anything below that I loose the ability to see the toolbar in full-screen when hovering.

Can I have all the corresponding elements? (even the one you don't use to specify in detail, instead of just its main element.... there has to be a "div" with its real name I mean)

Thank you ;)

**Comment by MrOtherGuy** [comment]
The only relevant element here should be `#PersonalToolbar`

If anyone experiencing this can figure out what causes that empty bar to appear on their setup, then please, let me know. Personally I can't reproduce this problem and I can't think of anything that could plausibly cause this.

**Comment by Ghis1964** [comment]
Maybe the reason you can't reproduce the empty bar is cause I have another code that prevents the whole page from jumping up and down each time when I hover the topbar. 
For now I leave it as it is. By the time I'll figure this out... (if I decide to change my mind.... 2-1/2hrs restarting firefox and deleting startupcache any next 30sec succeeded at giving me headache the last time) ...firefox will update and some other modification they will have made will render the work into another fail on my part :-(

I don't know how you can persevere 🖖

**Comment by MrOtherGuy** [comment]
Unfortunately I can't do much to improve compatibility with any arbitrary styles.

One user on reddit told they were experiencing similar problem with MaterialFox btw.

At any rate, using just this one stylesheet shouldn't cause content to jump anywhere since this style is supposed to overlay bookmarks toolbar on top of web content.

**Comment by Ghis1964** [comment]
I should have done this in the first place >>> leave you the part of my (grabbed from multiple author along the months/years) userchrome-css and let you try it yourself in another profile:

---------------------------------------------------
/* Disable native toggler that triggers JS listener */
#fullscr-toggler {
  pointer-events: none;
}

/* Force bgcolor to prevent transparent tabbar */
#TabsToolbar, #nav-bar, #PersonalToolbar {
  background-color: var(--lwt-accent-color) !important;
}

/* Allow registering hover state over toolbars */
:root:not([sizemode="normal"]) :-moz-any(#TabsToolbar, #nav-bar, #PersonalToolbar) {
  -moz-window-dragging: no-drag !important; 
}
  
:root:not([sizemode="normal"]):not([customizing]) #navigator-toolbox {
  margin-top: -1px !important;
  transition: none !important;
  z-index: 1;
}

:root:not([sizemode="normal"]):not([customizing]) #navigator-toolbox::after {
  height: 2px;
  visibility: hidden !important;
  opacity: 0 !important;
}

:root[customizing] #navigator-toolbox,
:root:not([sizemode="normal"]):not([customizing]) #navigator-toolbox:focus-within,
:root:not([sizemode="normal"]):not([customizing]) #navigator-toolbox:hover
/*:root:not([sizemode="normal"]):not([customizing]) #mainPopupSet:focus-within ~ #navigator-toolbox,
:root:not([sizemode="normal"]):not([customizing]) #mainPopupSet:hover ~ #navigator-toolbox */ {
  margin-top: 0 !important;
  transition-delay: 0s !important;
}

:root:not([sizemode="normal"]):not([customizing]) #navigator-toolbox:focus-within::after,
:root:not([sizemode="normal"]):not([customizing]) #navigator-toolbox:hover::after
/*:root:not([sizemode="normal"]):not([customizing]) #mainPopupSet:focus-within ~ #navigator-toolbox::after,
  :root:not([sizemode="normal"]):not([customizing]) #mainPopupSet:hover ~ #navigator-toolbox::after */ {
  height: auto !important;
}

:root:not([sizemode="normal"]):not([customizing]) #browser {
  position: fixed;
  z-index: 0;
  top: -44!important;
  width: 100%;
  height: 100%;
}

:root:not([sizemode="normal"]):not([customizing]) #browser > #appcontent {
  width: 100%;
  height: 100%;
} 

/* Fix strange 10px shift while not in fullscreen mode */
:root:not([inFullscreen]) #browser {
  top: -64px !important;
  height: calc(100% - 90px) !important;
}


/* Fix to comply with new Fixed/Absolute behavior in FF71 */

:root[inFullscreen]:not([customizing]) #navigator-toolbox {
  margin-top: -70px !important;
  transition: none !important;
  z-index: 1;
}
:root[inFullscreen]:not([customizing]) #browser {
  position: fixed !important;
  display: block;
  z-index: 0;
  top: 0;
  width: 100%;
}
 /* Sliding Bookmarks Bar
  * Makes the bookmarks bar slide down on hover or when menubar is enabled.
  * Contributor(s): zvuc (https://userstyles.org/styles/57368/firefox-sliding-bookmarks-bar-windows)
  * License: CC BY-NC-SA (https://creativecommons.org/licenses/by-nc-sa/4.0/)*/
#PersonalToolbar {
  margin-top: -10px !important;
  visibility: hidden !important;
  padding: 2px !important;
  height: 15px !important;
  max-width: 80% !important;
  width: 80% !important;
  position: fixed !important; 
  opacity: 0;
  z-index: 0!important;
}

#nav-bar:hover ~ #PersonalToolbar, 
#PersonalToolbar:hover
{
  visibility: visible !important;
  opacity: 1;
  -moz-transition: none !important;
  -moz-transition-delay: 0s!important;
  z-index: 0!important;
}
 --------------------------------------------------------------------

remark: you'll that most of the "var(--abcdxyz)" are almost all gone. I don't like using those as this force me to and search through another file in order to change its behaviour/colour/etc instead of have it right in the line I'm working in. It's easier to remember what black white red orange etc look like instead of "var something-xyz" ;)

You'll see that the page does not jump up/down.... still, I have no idea what I did (add/removed/modified) to have this result. I'm running in the dark sliding my fingers on the walls if not just luck. But you know better, so I'm sure you'll see what/where did I do anything in order to have it this way. 
Also, the negative are set way too high, that I know. But that's the way only I found to reduce the height of the "blank-bar". 

  Have fun 👍

**Comment by Ghis1964** [comment]
ps: I don't how to edit the comment so that the code won't blow itself in 28+px characters

**Comment by MrOtherGuy** [comment]
Sorry, but I'm not really sure what you are after here. The CSS you posted doesn't have anything to do with my autohide_bookmarks_toolbar.css. Instead, you are using something very different.

In addition, it does some very weird stuff to the whole window, and I really am not sure what for. You say it does something to prevent page from jumping up/down but I can't see where such jumping ever even happens.

IF by jumping you mean what happens when Firefox is in fullscreen mode (activated by F11), then sure, that kinda does happen but there's got to be a more sane way to prevent that. In fact, I believe you could re-purpose my [autohide_toolbox.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_toolbox.css) for this if you replace every `#navigator-toolbox` with `#navigator-toolbox[inFullscreen]`

At any rate, your issue has nothing to do with my autohide_bookmarks_toolbar.css

**Comment by Ghis1964** [comment]
> I'm not really sure what you are after here. The CSS you posted doesn't have anything to do with my autohide_bookmarks_toolbar.css <

Funny you think that. I found you through reddit and you were the only one who had the correct naming of some of the elements I needed to switch. Codes are useless if not the right element. So there. Do not believe that only the coding is the work. I would have use all your codes, but I was still having issues in some places. There's 2400+/- lines in my userchrome-css working along 2 other userchrome-js files. And it's a bit hard to keep memories of what were the css 18 months ago when notepad++ decides to scrap all previous sessions and backups for no reason. Luckily, firefox was running, so it could destroy that file ;)

Thx for the other css file. I'll take a look at this.

**Comment by MrOtherGuy** [comment]
Look, there are multiple ways one can implement autohiding bookmarks toolbar (or any other layout), and I cannot support all of them. In addition, people often already have their custom layout - especially folks at /r/firefoxcss. Their custom css may create some, let's say restrictions, for additional styles. 

So generally, when people ask if someone asks help to fix something, especially if it's implied that it broke with Firefox update, then I *tend to* give them solutions that require the least amount of changes for their setup.

Whether or not part of your current autohiding bookmarks toolbar css was created by me, it's not what this github issue is about. This issue is about the autohide_bookmarks_toolbar.css from this repository. 

I'm definitely still interested in knowing what causes the "black bar" to appear but at this time I have not been able to reproduce it myself. So, unfortunately this issue is probably stuck until someone can find steps to reproduce this.

**Comment by Ghis1964** [comment]
I'm just throwing out ideas... Mozilla has change the whole about:config UI, and even call this now Advanced Preferences. I don't see why they have change this. There's no any useful reason to do so. In fact, it look so much like a web-interface it would even make me think it could be way more sniffable from any online lurker. 
But my question is: Could this new interface be responsible for this persistent bar?

I remember having unpack a firefox assembly/pack made for linux (as it is nothing but a zip-file) just to have a look. But this was long ago when everything was legacy. The UI style (css and js) are all in there. I'd be curious to journey back into them (css/js) and compare version FF70 against FF71/FF72. But I'm not that knowledgeable at using any editor to use their "plugin" made to compare files and find the differences if any.

As said, I'm just throwing idea, if of any use ;)

Thx

**Comment by MrOtherGuy** [comment]
You can "fix" you personal stylesheet by setting `#PersonalToolbar{ display: block }` and by increasing it's z-index on the two places that for some reason set it to `0 !important`

But as said, that is totally unrelated to this issue.

**Comment by Ghis1964** [comment]
Noted ;)

**Comment by Ghis1964** [comment]
It's working ☺️👍👍
There's only a couple of pixels left of it, but this is because I have messed way too much with them heights. I was to remedy those heights anyway because it had set the bookmark-bar 2-3px too high and no padding on its bottom. (did I just said "no padding on its bottom"?  😅🤣 I need some sleep)

Thx. For me, this is solved ;)
