### ISSUE TITLE
Question: Any way to make autohide_sidebar only affect Sidebery?

### ISSUE THREAD

**Issue by a-plastic-bag** [MrOtherGuy/firefox-csshacks#324]
I'd like only Sidebery to autohide, and not other sidebars like history. How would I go about doing this?

**Comment by MrOtherGuy** [comment]
An easy way would be to restrict the selector on line 7 to only apply to sidebarcommand identifier derived from the extension id. So in Sidebery's case the new selector would be:

```css
#sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"]
```

There might be some issues caused by all the other rules still applying to all sidebar types but at first glance I don't see any major issues.

**Comment by a-plastic-bag** [comment]
That did the trick! Thanks!
