### ISSUE TITLE
multi-row_bookmarks: not working in Windows 11

### ISSUE THREAD

**Issue by drakanor** [MrOtherGuy/firefox-csshacks#330]
Is multi-row_bookmarks not working with Firefox in Windows 11? I got a new Laptop and a new box at the office, both with Windows 11 installed. After a fresh Firefox install, the hack is not working there. The bookmark row stays in 1 line. No problems with Windows 10 tho (same Firefox version).

**Comment by MrOtherGuy** [comment]
I think it should work since from Firefox side of things Win10 should not be very different from Win10.

But, if you just tried with "fresh Firefox install" then the issue might just be that you need to set the pref that makes Firefox look for userChrome.css in the first place: `toolkit.legacyUserProfileCustomizations.stylesheets`

**Comment by drakanor** [comment]
Ah, yes, you are right. Forgot to enable this option. Thanks for the hint.
