### ISSUE TITLE
window_control_placeholder_support.css no longer working in Windows 11 as of 123.0a1

### ISSUE THREAD

**Issue by nx5314** [MrOtherGuy/firefox-csshacks#331]
![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/8242753/6b6dd077-74fe-44c2-9280-d694b861a93d)
in combination with hide_tabs_toolbar.css

also tested on a fresh 123.0a1 instance
it is still working in 121.0

**Comment by MrOtherGuy** [comment]
Yeah, this was caused by changes from [bug 1870803](https://bugzilla.mozilla.org/show_bug.cgi?id=1870803). But undoing those changes makes the styles work again. In my opinion this wasn't as much an issue with window_control_placeholder_support.css but more about hide_tabs_toolbar.css (and several other ones as well).

**Comment by jondamvi** [comment]
> Yeah, this was caused by changes from [bug 1870803](https://bugzilla.mozilla.org/show_bug.cgi?id=1870803). But undoing those changes makes the styles work again. In my opinion this wasn't as much an issue with window_control_placeholder_support.css but more about hide_tabs_toolbar.css (and several other ones as well).

Hi, what do you mean by undoing these changes fixes it? I see "window_control_placeholder_support.css" moved to deprecated, why is that? With latest firefox update minimize and close buttons no longer shown, can't this be fixed?

**Comment by MrOtherGuy** [comment]
By "undoing" I meant to unset a couple of css properties that were added in changes in the linked bug.

window_control_placeholder_support is moved to deprecated because it is no longer needed by any other style, except ones that are themselves deprecated.

If you have a problem with window controls disappearing then create a new issue for that and mention what style(s) the issue appears with.
