### ISSUE TITLE
inline_tab_audio_icons.css only  show audio icon

### ISSUE THREAD

**Issue by casualbugs** [MrOtherGuy/firefox-csshacks#333]
Hi
Currently the css shows the speaker icon whenever playback is blocked.

I'd like it to only show the audio icon when something is playing with audio in the tab. The play icon showing doesn't serve much of a purpose for me.

Tried tweaking the script but couldn't get it to work.

Can you please help?

**Comment by MrOtherGuy** [comment]
What exactly do you see? I don't think I understand the situation you are facing. When I try the style, it will show a "play" icon in the tab if Firefox blocked automatic playback in that (background) tab.

1. Go to youtube.com
2. Hold Ctrl and click some video
3. The video opens in a background tab

Results a "play" icon is shown and clicking it will start playback and the icon changes to "mute" icon.

I would imagine that if you have some extension blocking playback then this might not work because chances are that the extensions will stop the playback only after it has started - like in a first frame or something. I doubt there's anything you can do about that since technically the playback was stopped, not blocked.
