### ISSUE TITLE
With autohide_main_toolbar.css, dragging tabs only work for the top 1px or 2px.

### ISSUE THREAD

**Issue by dragoneral** [MrOtherGuy/firefox-csshacks#342]
With autohide_main_toolbar.css active, dragging tabs from other windows and dropping tabs will only work when the cursor is hovering at the top few pixels of the tab bar.

**Comment by MrOtherGuy** [comment]
Hmm, you're right. Could you test replacing `#TabsToolbar` [on line 24] with `#titlebar`? I mean, it *does* fix this particular problem, but I'm a bit hesitant to call it a correct solution because it seems I have deliberately changed it *from* `#titlebar` to `#TabsToolbar` 3 years ago. So please test it and see if you hit some other issues with that.
