### ISSUE TITLE
FF75 makes the urlbar behind the new drop-down

### ISSUE THREAD

**Issue by dit7ya** [MrOtherGuy/firefox-csshacks#36]
After 75 update this is what I am getting 

[
![2020-04-09-122915_1920x1080_scrot](https://user-images.githubusercontent.com/14034137/78867007-0a819380-7a5e-11ea-840c-9c7023e39e8c.png)
](url)

**Comment by MrOtherGuy** [comment]
Are you using up-to-date version of whatever stylesheets you are using from my repository?

**Comment by dit7ya** [comment]
Sorry, I should have mentioned that I have been using this script.

**Comment by MrOtherGuy** [comment]
Huh, interesting. I can reproduce with Firefox 75 but it works correctly in 76, 77 and it also worked correctly in 75beta.

I'm going to look into it, but this feels pretty weird to be honest.

**Comment by MrOtherGuy** [comment]
Okay, so it turns out that if Firefox applies userChrome.css too early in the startup then it may cause it to compute some of the urlbar sizing properties incorrectly.

I applied a patch such that the transforms are not applied before session has been restored. This should have only very minimal visible effects.

Please confirm that the latest version works and this issue can then be closed.

**Comment by dit7ya** [comment]
Thank you very much! The update works fine.
