### ISSUE TITLE
Show bookmarsk toolbar ONLY when hovering URL bar

### ISSUE THREAD

**Issue by FloppyDance** [MrOtherGuy/firefox-csshacks#366]
Hi!
I'm using autohide_bookmarks_toolbar.css.
Is there a way to show bookmarsk toolbar ONLY when hovering URL bar instead of showing it when hovering also the tab bar?

Thank you

**Comment by MrOtherGuy** [comment]
Yes, if you replace [line 48 here](https://github.com/MrOtherGuy/firefox-csshacks/blob/66968d544affcdd45ec3996658585e5b7ff35b25/chrome/autohide_bookmarks_toolbar.css#L48) with this:

`#nav-bar:hover + #PersonalToolbar, #PersonalToolbar:hover{`

That is assuming that by "URL bar" you mean the whole toolbar and not just the url bar portion of it.
In such case you might also want to increase the delay on line 49 because otherwise the bookmarks might fling into existence if your cursor doesn't move fast enough over the main toolbar.

**Comment by FloppyDance** [comment]
Thank you!
I changed line 48 as you suggested, without increasing the delay on line 49, and it seems to be working fine.

**Comment by MrOtherGuy** [comment]
Great stuff. I'll close the issue then.
