### ISSUE TITLE
[Feature Request] Display "List All Tabs" icon and "Firefox View" icon on CSS hack "hide tabs toolbar"

### ISSUE THREAD

**Issue by Saya47** [MrOtherGuy/firefox-csshacks#406]
Hello, I hope you're doing great, first of all thanks for this beautiful work. I am enjoying the "hide tabs toolbar" css hack, I just have two issues with it. I will miss the "List All Tabs" icon and "Firefox View" icon. If these icons had a keyboard hotkey or another method of enabling them, that would be awesome, but I searched and I couldn't find any hotkey for them, so I wanted to ask is it possible to add these two icons to the bar below where we have Close/Maximize/Minimize?

I'm using this:

https://mrotherguy.github.io/firefox-csshacks/?file=hide_tabs_toolbar.css,window_control_placeholder_support.css

There are no hotkeys for the icons:

https://connect.mozilla.org/t5/ideas/keyboard-shortcut-for-quot-search-tabs-quot/idi-p/9134

https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

Thanks very much.

**Comment by Saya47** [comment]
Thanks very much @MrOtherGuy I didn't know that, so I got Firefox View back! 
For List All Tabs, I tried the other script but it broke the bar!
![image](https://github.com/user-attachments/assets/ccecf928-013b-4103-b14c-d76f163cf518)
I think it's because I have too many icons in there!
So I tried removing a bunch but still didn't help!
![image](https://github.com/user-attachments/assets/7bf15bb3-7c86-4981-8165-ab787953a646)

**Comment by MrOtherGuy** [comment]
Just like with hide_tabs_toolbar.css, you need to first include `window_control_placeholder_support.css`. That should fix one thing.

Another thing is that the button won't be freely movable. It would appear more or less in the same horizontal position where it would be if tabs were shown. The custom rules in that style assume that the button is at the right side of tabs, but your screenshot kinda suggests that you have moved that button to the left side of tabs and so it now overlaps back-button. So either move alltabs-button to the right side or change [line 29 here](https://github.com/MrOtherGuy/firefox-csshacks/blob/3c18dabe86b33d8f90b7f69a73442dfe0d053cc4/chrome/hide_tabs_toolbar_w_alltabs_button.css#L29) to `padding-left` instead of padding-right.

**Comment by Saya47** [comment]
Thanks very much! Works perfectly!
I think it's time for me to say goodbye to Chrome+Vivaldi+Edge and move all my tabs and bookmarks hehe :D
