### ISSUE TITLE
Multirow tabs missing Tab Overview Menu

### ISSUE THREAD

**Issue by derickso** [MrOtherGuy/firefox-csshacks#407]
Normal FIrefox: 
![YRNCTdJ](https://github.com/user-attachments/assets/4f8e4de8-9048-4701-8fa8-85f921ed036a)

Multirow tabs: 
![Rk13bde](https://github.com/user-attachments/assets/6af655c8-80ca-4e63-b037-a8cd67a4074b)

**Comment by MrOtherGuy** [comment]
Yes, we hide it on purpose since it's not very useful when your tabs are shown on multiple lines and it being there takes away horizontal space from all tab rows.

But if you want it back then just [remove line 73](https://github.com/MrOtherGuy/firefox-csshacks/blob/3c18dabe86b33d8f90b7f69a73442dfe0d053cc4/chrome/multi-row_tabs.css#L73)

**Comment by MrOtherGuy** [comment]
On second thought I should perhaps just remove that line altogether since with Firefox 133 you can freely move that button around or remove it if you wish to.

**Comment by MrOtherGuy** [comment]
I've changed the style to only hide the alltabs button when it's not removable - From Firefox 133 onwards the button can simply be moved or removed by the user as any other button - but I want to keep it hidden for ESR 128 users.
