### ISSUE TITLE
Border Colouring of menupopup's

### ISSUE THREAD

**Issue by ChasCB** [MrOtherGuy/firefox-csshacks#409]
As hard as I have tried using Browser Toolbox search, r/FirefoxCSS and general research, I am unable to alter or insert the colouring of ALL the <popupset id="mainPopupSet"> </popupset>  borders and only the borders.

My current my_userChrome.css for this is:

menupopup, panel, menulist { --panel-border-color: transparent !important; --panel-border-radius: 8px !important; --panel-shadow-margin: 3px !important; --panel-shadow: none !important; background: linear-gradient(45deg, red 0%, orange 16.66%, yellow 33.33%, green 50%, blue 66.66%, indigo 83.33%, violet 100%) !important; border-radius: 8px !important; } 

This ONLY gives me some colourful borders between <popupset id="mainPopupSet"> </popupset> 
e.g. tab-preview-panel on hover and appMenu-popup, toolbar-menupopup & PlacesChevronPopup only on left click.

It does NOT give me any right click menupopup colourful borders for everything else within <popupset id="mainPopupSet"> </popupset>

Any help would be great full.

Cheers 🍷

**Comment by MrOtherGuy** [comment]
I'm going to close this as it isn't a feature request or issue with the repository per se.

What you have does produce gradient border around right-click menus for me. You should note that on macOS (and maybe some linux distros as well?) Firefox normally uses native context menus which cannot be styled with css - so that might explain why it isn't working. You can disable native context menus by setting `widget.macos.native-context-menus` or `widget.gtk.native-context-menus` but I can't say how supported non-native context menus are especially on macOS.

**Comment by ChasCB** [comment]
> You can disable native context menus by setting `widget.macos.native-context-menus` or `widget.gtk.native-context-menus` but I can't say how supported non-native context menus are especially on macOS.

Ok, thank you for your very quick reply. The above mentioned two about:config settings were already set 'false' and yes I had disabled all other chrome settings except for userChrome leaving only that code in it. So, as you said this is not supported in macOS. So sad because between Aris-t2 and my own css I am 99% there with how I want my macOS FF to be.
Thank you again
Cheers 🍷
