### ISSUE TITLE
vertical_tabs.css Broken After Firefox 131 Update

### ISSUE THREAD

**Issue by Cr-nch** [MrOtherGuy/firefox-csshacks#416]
After the recent Firefox update, the tabs now attempt to render horizontally but still in the sidebar, and so while tabs are still accessible, they are basically unusable.

I have attempted to update my vertical_tabs.css file and the issue still persists, and it seems to be related to a new `orient` tag on the `arrowscrollbox` __element__ which is set to "horizontal" by default, where setting it to "vertical" fixes the issues. (This is probably related to the actual work being done to get actual vertical tabs working.)

**Comment by MrOtherGuy** [comment]
I suppose I can check it out and fix it if it's something simple, but that style is going to be deprecated real soon since Firefox is getting it's own real vertical tabs in 132 or 133 I would think. It's already more or less usable in 131 if you set both  `sidebar.revamp` and `sidebar.verticalTabs` to `true` in about:config. It should definitely be more usable that what this style achieves.

**Comment by Cr-nch** [comment]
Yeah, fair enough. It does seem stable enough now as an experiment to properly use now.

Funnily enough, changing the value manually also seems to persist through restarts of the browser.
Thanks for the suggestion to switch though!

**Comment by Cr-nch** [comment]
Switching to the built-in vertical tabs as described above now seems stable enough to use instead of a CSS hack.
