### ISSUE TITLE
Auto hide sidebar width issue

### ISSUE THREAD

**Issue by Achyuth072** [MrOtherGuy/firefox-csshacks#433]
Script: autohide_sidebar.css
Version: Floorp v11.19.1 ( FF 128.4.0)
Was working fine till today.
![image](https://github.com/user-attachments/assets/241cf420-afd0-4e10-ab91-f0d7124f153b)

**Comment by MrOtherGuy** [comment]
autohide_sidebar.css seems to work in Tor Browser which is also based on ESR 128 now. So, I'm going to say that the issue is compatibility with Floorp. Unfortunately Floorp, and other forks that deviate a lot from mainline Firefox, are not supported and I'm not going to add special styling to accomodate what ever changes some fork might do to Firefox.
