### ISSUE TITLE
autohide_tabstoolbar.css: unhide tabs when dragging over parent toolbox

### ISSUE THREAD

**Issue by dalps** [MrOtherGuy/firefox-csshacks#434]
Firefox 131.0.3

I was hoping the `autohide_tabstoolbar` script would reveal the tabs toolbar when dragging something over the parent toolbox area, so that the dragged content can be opened in a new tab.

My guess at a tweak for this effect was to replace all occurrences of `:hover` to
```css
:is(:hover, :-moz-drag-over)
```
but it still doesn't respond to dragging.

Is there a way it can support drag and drop? Thanks in advance!

**Comment by MrOtherGuy** [comment]
Sadly this doesn't work. In general, the interaction of dragging and hovering in CSS is pretty poor, and it is also at least somewhat OS specific. On Windows starting a drag-session sort of "locks" hover states until the drag-session ends, meaning :hover state on elements may stay even though cursor is outside of the element during the dragging -  and also like you have found out new elements don't become hovered. On Linux on the other hand, depending on your system, starting a drag session will cancel all current :hover states (but also lock them for the duration of the drag-session).

That is a long way to explain that no, we cannot do that with CSS alone. The would need to be some active javascript that watched if something is being dragged over the toolbox and set some attribute for it that the styling rules could the use. But with css only there's nothing we can do here.

**Comment by dalps** [comment]
Thank you for your insight! That's unfortunate, but also a good idea for an extension.

Nevertheless, another tweak that does work and I find pretty convenient is keeping the tabs toolbar un-hidden while the browser window is inactive, so that it's possible to drag-in things from the outside, at least.

This can be accomplished by combining `:hover` with `:-moz-window-inactive` in a similar way:
```css
:is(:hover, :-moz-window-inactive)
```
Works neatly on Windows as shown in the gif. Would it make for a good PR? ;D

![dragtab](https://github.com/user-attachments/assets/2b5c74af-2670-4c1a-aee4-9e349777036e)

**Comment by MrOtherGuy** [comment]
Perhaps there is something we can do to improvethe situation, but I'm not sure if that's it. Probably the most prevalent issue with that is that the top section of unfocused windows is the hidden since toolbars are drawn on top of it. Getting some dragging functionality could very well be worth it though.

Most notably though, this style is all kinds of broken on Firefox 133 and I'm not accepting PR's before those issues are solved - chances are that I would rewrite this style anyway.

Although, I guess there's no harm in any event if you want to do the work and make it an optional feature behind a custom preference - see the `@media (-moz-bool-pref: "prefname")` syntax I've used in couple of other styles [such as here](https://github.com/MrOtherGuy/firefox-csshacks/blob/b83f788e4d4b7625a7a01d3332e581c496a2e1d4/chrome/tabs_on_bottom_v2.css#L6)

**Comment by MrOtherGuy** [comment]
Well, I added a new version [autohide_tabstoolbar_v2.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_tabstoolbar_v2.css) where I included an optional feature to show tabs toolbar when window is inactive.

Like other recent "v2" versions this requires Firefox 133 - but this work with both horizontal and vertical tabs.

**Comment by dalps** [comment]
It took me some digging to figure out how to set the preference (a comment in another hack pointing to about:config really helped this newbie :p).

It works almost well on Firefox 133, if not for a little overlap with the sidebar (perhaps setting z-index somewhere might fix this?): 
![image](https://github.com/user-attachments/assets/f856befe-9ebf-4f49-b88a-bd62fbcb2af8)

Thank you for implementing my suggestion, and awesome work!
Feel free to close this issue.

**Comment by MrOtherGuy** [comment]
Great! The z-index issue shouldn't happen with new sidebar (need to set sidebar.revamp to true in about:config) and I don't think it makes sense to support old sidebar.
