### ISSUE TITLE
autohide_toolbox.css - window moved down 8px

### ISSUE THREAD

**Issue by megaslowpoke** [MrOtherGuy/firefox-csshacks#45]
The whole window moved down 8px(?), and therefore, for example: the hint link (when you hover over a link) is not visible full in the lower left corner.

**Comment by MrOtherGuy** [comment]
What OS do you use that with?

**Comment by megaslowpoke** [comment]
Windows 10, Firefox 76.0.1 x64, also tried to turn off all add-ons.

**Comment by MrOtherGuy** [comment]
Wow, how have I not catched that. Well, it should be fixed now.

**Comment by megaslowpoke** [comment]
Thank you so much, now everything is fine.

**Comment by megaslowpoke** [comment]
Empirically, I found out that for Windows 7 and Firefox 76.0.1 it works normally with the following parameters:

...(-moz-os-version: windows-**win7**){
  :root[tabsintitlebar][sizemode="maximized"]:not([inDOMFullscreen]) > body > box{**margin-top: 6px** !important; }...

It might be worth adding if you want to support Windows 7.

**Comment by MrOtherGuy** [comment]
Well I don't generally pay too much attention to Win7 because 1. it's deprecated and 2. it probably doesn't have too many users and 3. I don't have any Win7 system to test things with.

I could add rules for it though, but the important bit is what is seen in the stylesheet that Windows10 at least requires different values depending on the OS scaling. It's bloody annoying and -moz-appearance normally handles that, but since the style needs to set -moz-appearance to none well need to add those margins manually. 

So your margin-top: 6px may work on the OS scaling of whatever you have applied (such as 125%) but it probably does not work on 150% or 100%. Or it might, I genuinely don't know.

I wouldn't normally go as far as to set values for every scaling factor, but since this particular style requires pixel-perfect layout for it to do the one thing it's supposed to do I feel it's worth it.

**Comment by megaslowpoke** [comment]
In any case, now if anyone searches for support for Windows 7, they will be able to read here what needs to be changed. I think this is quite enough.

Thank you for this kit and its support.
