### ISSUE TITLE
hide_tabs_toolbar_v2.css on firefox 133 macOS

### ISSUE THREAD

**Issue by rsalmei** [MrOtherGuy/firefox-csshacks#452]
To @MrOtherGuy who did this v2: THANK YOU!
Firefox 133 completely ruined my Tree Style Tab experience. After testing a few scripts, this one of yours restored everything!

Is it okay if I point out something minor? Why did the right side of the bar get this space?
<img width="113" alt="image" src="https://github.com/user-attachments/assets/b9640247-84d6-4d96-8aaa-cf654056b6ad">

The window controls on the left are perfect, including the space until the first button.
<img width="146" alt="image" src="https://github.com/user-attachments/assets/e1df255d-6d13-481f-af85-8ea0ae35b779">

It’s truly just the right side that could do without that space…
Thanks again!

**Comment by MrOtherGuy** [comment]
Great that it works also on macos. The space has to be there for you to have space to grab the window to drag it around in case the space on the other side is inaccessible. But if you want to remove it the you can add this rule after all others:

```css
#nav-bar#nav-bar#nav-bar > .titlebar-spacer[type="post-tabs"]{ display: none !important; }
```

Note, that repeated `#nav-bar` is intentional because you need to increase rule specificity.

**Comment by rsalmei** [comment]
It worked flawlessly! I’m accustomed to moving the window just from the left side, and my previous configuration had even less space there.
Thank you very much.
<img width="70" alt="image" src="https://github.com/user-attachments/assets/1c2beacb-fb43-4a58-a341-fff37b7f1073">
