### ISSUE TITLE
FF133, When using `autohide_bookmarks_and_main_toolbars` how to keep the bookmarks bar available in fullscreen mode? 

### ISSUE THREAD

**Issue by Sinaaaa** [MrOtherGuy/firefox-csshacks#458]
Hi!

Already had this with the bookmark autohide before:
```
:root[inFullscreen] #PersonalToolbar {
 visibility: visible !important;
}
```

But it's not working. Is there anything I can do?

**Comment by MrOtherGuy** [comment]
Hmm, I can't think of why that would happen. The toolbar does have background on my system when I try that.

**Comment by Sinaaaa** [comment]
> Hmm, I can't think of why that would happen. The toolbar does have background on my system when I try that.

Further testing revealed something else.

I tried this:

```
:root[inFullscreen] #PersonalToolbar,
:root[inFullscreen] #PersonalToolbar #PlacesToolbarItems > :not([hidden]) {
  visibility: visible !important;
  background-color: rgba(0, 0, 0, 0.8) !important; 
}
```

And this made it very visible how the end of the bar is cut off  & now I can see that in the transparent version as well:

regular:
![screenshot_2024112720:0323](https://github.com/user-attachments/assets/74dd655e-9ad7-47a9-aed7-527cf4706963)
fullscreen:
![screenshot_2024112720:0328](https://github.com/user-attachments/assets/7075db4e-6f80-43fa-af88-54ce5286526f)

**Comment by MrOtherGuy** [comment]
Okay, the fact that the toolbar doesn't have background-color there indicates one of three things - either:

1. the toolbar doesn't get the background-color
2. The toolbar visibility is not actually `visible`
3. The toolbar height is 0 in fullscreen mode - items just overflow the toolbar container

3 probably is not the issue, because the toolbar also has `overflow: clip` so if items would overflow the toolbar itself, they wouldn't show up at all. 1 is possible, but I don't see what could override the background-color - at least nothing in autohide_bookmarks_and_main_toolbar.css will.

2 shouldn't be a problem - *except* if you have placed those extra rules **before** rules from autohide_bookmarks_and_main_toolbar.css - if they **are** placed before, then you should indeed get what your images show because autohide_bookmarks_and_main_toolbar.css will just override those custom rules for the toolbar visibility.

**Comment by Sinaaaa** [comment]
>2 shouldn't be a problem - except if you have placed those extra rules before rules from autohide_bookmarks_and_main_toolbar.css - if they are placed before, then you should indeed get what your images show because autohide_bookmarks_and_main_toolbar.css will just override those custom rules for the toolbar visibility.

Thanks a lot!

That was it, I apologize for this css idiot wasting your time.
