### ISSUE TITLE
Tabs below content and navbar below content don't work together

### ISSUE THREAD

**Issue by artemlive** [MrOtherGuy/firefox-csshacks#461]
Guys, is it possible to use the [tabs_below_content_v2.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/tabs_below_content_v2.css) with the [navbar_below_content.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/navbar_below_content.css)?
If I import both, it doesn't work. The tabs don't show up on the window. There is a line where the tabs should appear, but it's empty.
![image](https://github.com/user-attachments/assets/a41ed48b-f353-4eeb-9d5f-5a02f68559c6)

And it seems that the [navbar_below_content.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/navbar_below_content.css) is glitchy. I can't edit the URL because if I focus on the address bar, it pops up search instead of editing the current URL.

**Comment by MrOtherGuy** [comment]
You should rather try [toolbars_below_content.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/toolbars_below_content_v2.css)

The naming can be quite confusing, sorry about that, but the intention behind "tabs below content" or "nav-bar below content" is that your goal is to have *only* that toolbar below content. Whereas "toolbars below content" would move all toolbars below content. Although there's a exception for menubar to stay on top because I can't figure how anyone could want that at bottom - plus having it on top makes it able to show window controls in normal place.

**Comment by artemlive** [comment]
You shouldn't be sorry, I really appreciate this repository and the work that was done to make it so helpful🥇 
Thank you for the reply, the [toolbars_below_content.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/toolbars_below_content_v2.css) is exactly what I was looking for.
