### ISSUE TITLE
reload_button_in_urlbar broken

### ISSUE THREAD

**Issue by scmanjarrez** [MrOtherGuy/firefox-csshacks#472]
I'm not really sure when this started to happen (maybe with the lastest, v133, update?), but I noticed that the reload button is behind the bookmark icon.
![image](https://github.com/user-attachments/assets/1d48d121-88b7-49b7-ac09-384db6812c58)
P.S.: This is a new profile with only the reload_button_in_urlbar css applied.

**Comment by MrOtherGuy** [comment]
That style is pretty much not fixable. It will sort of work IF your theme has not fully opaque background-color for the urlbar - for example what you appear to be using - but if the theme has opaque background then it will cover the button and there's nothing we can do about it.

But for your purposes you can kinda make it work by adding a few rules - I've updated the style.

Still, there isn't really any way we could really fix this style because urlbar is in top layer now - at least not that I know of.

**Comment by scmanjarrez** [comment]
I also noticed that no matter what z-index I used, the reload button wasn't clickable any more. Well, thank you so much for your help!
