### ISSUE TITLE
Request to change from GNU GPLv3 to a more permissive license

### ISSUE THREAD

**Issue by KaranveerB** [MrOtherGuy/firefox-csshacks#49]
As this project serves as a collection of individual css tweaks/hacks rather than a unified theme, this project encourages using the css tweaks as _additions_ to theme/customization as opposed to as a base of the theme/customization to which new thing are added to. As it currently stands, using a single file from this project in a new project would force the entirety of the new project to be licensed under GNU GPLv3. I feel this is overly restrictive and far reaching of a project of this nature and a permissive license, such as the MIT license, would be more appropriate as is often seen with similar projects such as programming libraries (in that they add/aid in a project rather then being the base of project itself).

**Comment by MrOtherGuy** [comment]
Thank you for your input. I have actually been thinking about this for quite a while. Originally I didn't put too much thought into the license but now that the repository has grown quite a bit and become - like you said a collection of hacks (as opposed to being a theme and then some hacks which was more accurate at the beginning) - I've begun to think that GPLv3 is indeed too restrictive.

On that same note, would you think that it was a good idea to include the license in a header of each file? Individual files right now don't include anything except some basic description and maybe instructions. But I've observed many occasions where people post the contents of their userChrome.css (on reddit for example) to find why they suddenly broke with say new Firefox version, even if the files had already been fixed weeks or even months earlier by me. So clearly the user just wasn't aware of where that css originally came from.

So, what I kind of would want to do is to include a short header to each file that tells the applicable license and the address to that particular file in the repository to inform the user where to get up to date file.

I'd appreciate any input you have on this, thanks!

**Comment by KaranveerB** [comment]
It sounds like Firefox breaking CSS isn't super uncommon so I think adding a link to the file is a great idea and would be very helpful. For the licence, I think mentioning the license is a good idea so the license as the license can still be found if a individual files are copied, but adding the full contents of the license may get annoying to look at and is unnecessary (legally not required and people who would modify and redistribute the files would probably check the repo anyways) if you were planning to do that.

If the header is kept short, I think you should do both.

**Comment by MrOtherGuy** [comment]
I was thinking of some short 1-2 line header (or 3-lines max) such as:

```css
/*
Licensed under <license> from
original file <address>
 */
```

That wouldn't be the final formatting but something along those lines. I'm thinking about MPLv2 but I'm not certain if it would actually be permissive enough, so I might want to go with MIT instead.

**Comment by KaranveerB** [comment]
MPLv2 seems to be as permissive as MIT and other similar licenses besides the addition of being copyleft within it's own file. Seeing as MPLv2 plays nice with additional licenses, I think it just depends on whether you want to support copyleft or not. One thing to note is that CSS can't be compiled anyways so the choice doesn't have too much of an impact on what would be distributed. More so just makes it easier to deal with existing licenses of projects.

If you do choose to stick with MPLv2, Mozzila provides a nice [3-line header](https://www.mozilla.org/en-US/MPL/headers/) which they recommend you use.

**Comment by MrOtherGuy** [comment]
You are correct, the very reason I would be tempted to use MPLv2 instead of MIT is because there may be scenarios where the style in this repository is very similar to some Firefox built-in styles which are all(?) licensed under MPLv2 and as such MPLv2 would be compatible whereas MIT might not be.

I'm fine with copyleft, and if I understand it correctly then MPL would still allow larger projects, such as style "compilations" or "themes", to use some other non-copyleft license.

However, the MPLv2 short text by Mozilla is still too long in my opinion. Some of the stylesheets are much shorter than that, few by quite a margin.

I think something like this would be fine:

```css
/* Source file https://github.com/MrOtherGuy/firefox-csshacks/tree/master/content/dark_settings_pages.css made available under Mozilla Public License v. 2.0
See the above repository for updates as well as full license text. */
```

This header would nicely inform where it is from as well as the license without being too long.

**Comment by MrOtherGuy** [comment]
Okay. All files should have a notice like above now and LICENSE file in the repository has been replaced.

Effective as of now the files in this repository have been licensed under MPLv2 - but of course earlier copies will still use GPLv3 license which in truth probably won't matter too much since I don't think anybody has paid too much attention on the license.

Practically what this means is that copies or modified copies of files need to be distributed under MPLv2 or compatible license, but style compilations or comparable full theme packages can use different licensing **as long as individual files they use from this repository are made available with the original license notice and a copy of MPLv2 License text**

One should note that that the above grants you *more* permissions than you had earlier under GPLv3
