### ISSUE TITLE
non_floating_sharp_tabs

### ISSUE THREAD

**Issue by Dupond** [MrOtherGuy/firefox-csshacks#492]
Hello!

From my point of view, the `non_floating_sharp_tabs` hack has a few issues, but I'm unable to solve them:

1. It doesn't support the `compact` mode; although this mode is not officially supported, Firefox's default configuration (I mean: with a new profile and no userChrome file) has a smaller tab bar height in compact mode than in normal mode. Would it be possible to keep this behavior with `non_floating_sharp_tabs`?
2. Pressing the `Alt` key brings up the menu bar, which is normally the same height as the tab bar, to prevent the `Min`, `Max` and `Close` buttons from moving vertically. However with `non_floating_sharp_tabs` the buttons move in the `compact` and `normal` modes.
3. Would it be possible to add an option so that there's a 3 or 4px margin above the tabs? (I mean: between the top border of Firefox and the top outline of the tab; currently, the top of the tab touches the top of the browser.)

Thank you very much for your help!

**Comment by MrOtherGuy** [comment]
What kind of issues are you experiencing in compact mode? As far as I can tell, non_floating_sharp_tabs.css works just fine in compact mode. The absolute height difference between normal and compact *is* smaller with non_floating_sharp_tabs.css than it is without any css  - 32px/36px vs 37px/44px, though these values can depend on font-size of the UI but I don't want to change that since it comes from your OS.

The Alt menubar not being correct height is kinda unfortunate, but I can't think of a good way to fix that - exactly because, as mentioned the toolbar height can depend on system font size.

As for the extra space atop, yes I could add such thing maybe. The problem with that is deciding what exactly the option does. In my opinion the only sensible way would be that the extra area is on there in normal (so non-maximized) windows - but I could also imagine someone might then also want that in maximized or fullscreen windows and I don't want to create options for all possible combinations.

Anyway, if you want such space always there you can just add:

```css
#TabsToolbar > .toolbar-items{
  padding-top: 4px
}
```

**Comment by Dupond** [comment]
> What kind of issues are you experiencing in compact mode?
On my system (Firefox 133.0.3 on Arch Linux) the height of the tab bar doesn't change between compact and normal mode. It's exactly the same.

> The Alt menubar not being correct height is kinda unfortunate, but I can't think of a good way to fix that - exactly because, as mentioned the toolbar height can depend on system font size.
Understood. I can live with that :)

Thank you for your previous answer, and have a nice day.

**Comment by MrOtherGuy** [comment]
I see, that probably means that we have already removed all the empty space inside tabs and the font-size (or really the height of the tab label element which is derived from font-size) is all that's constraining the height from becoming smaller.

If that is the case the you can maybe get it somewhat smaller by adding these rules:

```css
:root{
  --tab-min-height: 20px !important; /* default is 29 */
}
.tab-label-container{
  height: 2.2em !important; /* default is 2.7, at least on windows */
}
```

But I don't think I want to add either of these into non_floating_sharp_tabs.css because changing the height of tabs isn't the purpose of that style.

**Comment by Dupond** [comment]
Yes, I can play with `--tab-min-height`.

Before you explained it in your first answer, I hadn't understood that the font-size is what's constraining the height of my tabs from becoming smaller; thank you very much for your answers! Thanks to you, I've learnt something new :)
