### ISSUE TITLE
Tab groups and tab_separator_lines.css

### ISSUE THREAD

**Issue by Dupond** [MrOtherGuy/firefox-csshacks#494]
Hello!

In case you wouldn't have seen it, I wanted to notify you of [a post on reddit](https://www.reddit.com/r/FirefoxCSS/comments/1h10k0a/help_fixing_tab_separator_code_while_using_tab/) suggesting a few additions to the `tab_separator_lines.css` hack in order to adapt it to tab groups (credit goes to u/qaz69wsx):

```
tab-group[collapsed] > .tabbrowser-tab,
tab-group[collapsed] + .tabbrowser-tab,
tab-group:not([collapsed]) > .tabbrowser-tab:first-of-type,
tab-group:not([collapsed]):has(> .tabbrowser-tab:last-of-type:is([visuallyselected], [multiselected], :hover)) + .tabbrowser-tab {
  border-image: none !important;
}
```

I think some code should also be added to reduce the gap between a collapsed tab group and the next tab; I think it *could* be something like this:

```
tab-group[collapsed] > .tabbrowser-tab, tab-group[collapsed] + .tabbrowser-tab { border-inline-start: 0 !important; }
```

Finally, adding a separator between tabs results in a slight 1-pixel gap (due to `border-inline-start: 1px solid transparent !important;` in the hack) in the `.tab-group-line`, but I'm not sure it can be avoided (or maybe the `.tab-group-line` could be re-drawn as an overlay? It would also be more compatible with the `non_floating_sharp_tabs.css` hack, since the border on `#nav-bar` hides the bottom of the `.tab-group-line`).

I thought you might be interested in these additions.

Have a nice day!

**Comment by MrOtherGuy** [comment]
Those are all good points. I haven't bee much of a tab group user so styles are certainly lacking support for that.

I've updated the style to now draw the lines as background-image instead which fixes the border causing that "separation" in tab group line.

Also, I've updated non_floating_sharp_tabs.css - it now draws the group line at the top - because having it at bottom will unavoidably cause selected tab to be "disconnected" from nav-bar. Doing it this way also lets the tab context line to be at the bottom without it looking weird when both context-line and group-line would be shown. In non_floating_sharp_tabs.css it will still happen that selected tab has both, it's own top line which isn't perfect - but I think it still looks better than if selected tab would lose its own top line if it was inside a group. But perhaps this could be improved somehow.

**Comment by Dupond** [comment]
Those updates are great!

Personally, I prefer to keep the group line at the bottom. The problem is that the tab border in `non_floating_sharp_tabs.css` (`.tab-background[selected]{ border-inline: 1px solid` etc.) interrupts the group line by creating a 1 pixel space again... Is it possible to avoid this?
