### ISSUE TITLE
tags.csv not showing table layout

### ISSUE THREAD

**Issue by techboyg5** [MrOtherGuy/firefox-csshacks#55]
On the tags.csv file, GitHub's table layout does not work for the following reason:
> We can make this file beautiful and searchable if this error is corrected: It looks like row 2 should actually have 4 columns, instead of 6. in line 1.

Can you please fix this problem?

**Comment by MrOtherGuy** [comment]
No. It's not a problem. It's by no means meant to show in table format.

tags.csv is simply a filename+comma followed by a comma separated list of tags. I could have as well named it tags.txt but its contents are literally Comma Separated Values so I went with csv instead.

**Comment by techboyg5** [comment]
Just try it.

**Comment by MrOtherGuy** [comment]
Yes, I see the message you mentioned. I suppose it happens because github would "like" to use render the file as table but cannot because the lines in the file have variable number or commas.

But Github is wrong. The file is not supposed to be like that. The correct way to fix this would be to tell github that it should not try to render this as a table because it isn't one. But that's not something that I can do (other than changing file extension).

**Comment by techboyg5** [comment]
> Yes, I see the message you mentioned. I suppose it happens because github would "like" to render the file as table but cannot because the lines in the file have variable number or commas.
> 
> But Github is wrong. The file is not supposed to be like that. The correct way to fix this would be to tell github that it should not try to render this as a table because it isn't one. But that's not something that I can do (other than changing file extension).

OK, thanks!
