### ISSUE TITLE
[QUESTION] multi-row_oneliner_combo_patch.css 	

### ISSUE THREAD

**Issue by EstherMoellman** [MrOtherGuy/firefox-csshacks#58]
Please:

Is it possible to have the oneliner + multirow combined, with the following tweaks?:

- First tab row with bigger tab width than the other tab rows (smaller tab width).

- Auto-hide function for all tab rows except the first tab row. By auto-hide function here I'm mean something similar to what you kindly built me for my current Sidebar, which is hidden by default, it appears on mouse-hovering, and it permanently appears on mouse-click over vertical bar on the left-side. This SideBar auto-hide function is based on a small JS, and I know this is a CSS' repo, but long time ago, using only CSS, you built me something similar for the NavBar. So, from my ignorance I prefer to ask you, because perhaps (using only CSS) it might be possible to build a similar autohide for multirow.

- "#alltabs-button" + icon button add-on ([TabToBookmarkGroups](https://addons.mozilla.org/en-US/firefox/addon/tabs-to-bookmark-groups/)), both buttons appearing on rightmost top corner, only in first tab row.

MY RATIONALE:
My new customized model based on combined_tabs_and_main_toolbars.css is positively revolutionary to me. But the fact I'm not having direct instant access to tab pop-up, and the limitation of showed tab status on tab pop-up, these two reasons push me to try new experiments.
In this context, now I'm trying a new test, combining oneliner + multirow + tab pop-up on the right-side (emulating vertical tabs).
If the tweaks above are doable, then for me it will be a workaround to have direct instant access to all the tabs, having also a visual of all tab status (two features extremely needed and useful on my day-to day).
I hope all my questions to you, my experiments and my tests etc will help other users to have alternatives for vertical tabs on the right-side (without losing the SideBar).

Thank you in advance!

**EDIT:**

Sorry, I forgot one more question/tweak: In the multi-row_oneliner_combo_patch.css, is it possible to have window-controls (on the left-side) but in vertical position? (from top to bottom: close, maximize, minimize)

**Comment by MrOtherGuy** [comment]
> First tab row with bigger tab width than the other tab rows (smaller tab width).

No. Tabs don't know on which row they are on, and flexbox doesn't have any property to control grow factor by row.

> Auto-hide function for all tab rows except the first tab row

This sounds at first like it should be possible but it would be hacky as hell and a lot of work. Like seriously a LOT. And I'm not 100% sure if it even is possible.

> "#alltabs-button" + icon button add-on (TabToBookmarkGroups), both buttons appearing on rightmost top corner, only in first tab row.

No can do. I mean, the horizontal space they would take will be removed from all tab rows. If you're fine with that then sure, it's possible. Hacky, but possible.

> one more question/tweak: In the multi-row_oneliner_combo_patch.css, is it possible to have window-controls (on the left-side) but in vertical position? (from top to bottom: close, maximize, minimize)

Well. I have no idea how you plan to fit window controls vertically, unless there are always going to be multiple tab rows. But you can use `.titlebar-buttonbox{ -moz-box-orient: vertical }` and then reduce the padding on nav-bar (border-left-width, since the placeholder sheet needs to use that for reason I don't remember right now) And you'll then want to make sure that you add that padding to TabsToolbar too so that window controls won't overlap tab rows. I imagine that this will in turn cause some problems for the first tab position which you'll probably need to adjust to compensate.

In addtion, you should probably use -moz-box-orient on window control buttons to reorder them instead of -moz-box-direction, I think the latter behaves "interestingly" on vertical orient.

**Comment by EstherMoellman** [comment]
... sorry to hear that my desired tweaks can't be made or they are too complicated etc. These limitations together with tab pop-up limitations (no direct access, not all tab status inside, no tab close button, no tab dragging etc)... slowly but surely is killing my project of vertical tabs on left-side. It is the second time I invest a lot of time and energy, trying to build an alternative for vertical tabs on the left-side... and I always end defeated.

Due to my lack of knowledge on JS/CSS, together with Firefox (inexplicable) limitations... everything conspires against any second sidebar possible workaround, and forces users to use current sidebar if they want vertical tabs. Ever single step forward (vertical tabs on second kind of sidebar) implies two steps backward.

I also don't understand why (until today ) any Dev came with an add-on, allowing to use vertical tabs, without using sidebar + using the full left or right column from top to button.

Anyway, thank you for your help, time and patience, and please feel free to close my two issues.

PS: Feeling completely defeated : (
