### ISSUE TITLE
CSS of addon manage buttons without popup no longer works

### ISSUE THREAD

**Issue by ReporterX** [MrOtherGuy/firefox-csshacks#63]
Firefox 77.0.1, this CSS script no longer works. Nothing is changed.
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/content/addon_manage_buttons_without_popup.css

**Comment by MrOtherGuy** [comment]
Are you sure that your environment hasn't changed? The style seems to work fine up to Firefox 79 - except that addon options-button icon doesn't appear. I'll fix that shortly.

**Comment by MrOtherGuy** [comment]
> except that addon options-button icon doesn't appear. I'll fix that shortly.

Well I seem to have fixed that already.

**Comment by ReporterX** [comment]
> 
> 
> Are you sure that your environment hasn't changed? The style seems to work fine up to Firefox 79 - except that addon options-button icon doesn't appear. I'll fix that shortly.

It was my first time using your CSS script but it failed to work. Nothing was changed.
I use [Firefox portable 77.0.1](https://portableapps.com/apps/internet/firefox_portable). I'm not sure if portable makes the difference.

**Comment by MrOtherGuy** [comment]
If you haven't used userChrome.css or userContent.css (where that particular style should go to) then you need to make Firefox load those files in the first place. To do that you will need to set the pref `toolkit.legacyUserProfileCustomizations.stylesheets` to true in about:config

**Comment by ReporterX** [comment]
> 
> 
> If you haven't used userChrome.css or userContent.css (where that particular style should go to) then you need to make Firefox load those files in the first place. To do that you will need to set the pref `toolkit.legacyUserProfileCustomizations.stylesheets` to true in about:config

I set it to true long time ago. I tried other CSS scripts. They worked fine, so there shouldn't be any problem about my setup.

This is the current content of my userChrome.css:

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"); /* only needed once */

/* Source file https://github.com/MrOtherGuy/firefox-csshacks/tree/master/content/addon_manage_buttons_without_popup.css made available under Mozilla Public License v. 2.0
See the above repository for updates as well as full license text. */

/* Show addon management buttons without opening popup */

@-moz-document url-prefix("chrome://mozapps/content/extensions/aboutaddons.html"){
 
  .addon-card-message{ margin-bottom: 0px !important; margin-top: 0px !important; }
  .card.addon{ padding-bottom: 0px !important; }
  
  addon-card .addon-card-collapsed{ display: grid !important; grid-template-areas: "ic con" "op op"; grid-template-columns: 48px auto }
  addon-card .card-contents{ width: initial !important; white-space: initial !important; }
  
  .more-options-menu{ position: static !important; grid-area: op; margin: 0 !important; }
  .card-contents{ grid-area: con }
  .card-heading-icon{ grid-area: ic }
  
  plugin-options > panel-list,
  addon-options > panel-list{
    position: static !important;
    display: flex !important;
    padding: 0 !important;
    margin: 0px calc(0px - var(--card-padding)) !important;
    backdrop-filter: none !important; /* Having a backdrop-filter leads to some unexpected layering issues */
  }
  
  button[role="menuitem"]{ padding-inline-start: 30px !important; background-position-x: 8px !important; }
  
  .arrow,
  .more-options-menu > .more-options-button,
  .addon-name-container > .more-options-button,
  panel-item[action="expand"]{ display: none !important }

  div.list{ display: inherit !important; flex-direction: row !important; } 
  
  panel-item[action="toggle-disabled"]{ --icon: url("chrome://browser/skin/quit.svg") }
  panel-item[action="preferences"]{ --icon: url("chrome://global/skin/icons/settings.svg") }
}
```

**Comment by MrOtherGuy** [comment]
As I mentioned contents of addon_manage_buttons_without_popup.css (and all the files in /content folder) have to be loaded with **userContent.css** not userChrome.css

And that `@namespace` line should definitely not be used in userContent.css - it's also probably a good idea to **not have it** in userChrome.css either - but that is not the issue here.

**Comment by ReporterX** [comment]
> 
> 
> As I mentioned contents of addon_manage_buttons_without_popup.css (and all the files in /content folder) have to be loaded with **userContent.css** not userChrome.css

Thanks for the clarification. It works as expected now. 
I didn't see any instruction on that page. I thought it was meant to be put in userChrome.css. My bad.
I think it might be a good idea to state clearly in the page.

BTW line 4 and 6 in the page are duplicate: 
```
/* Show addon management buttons without opening popup */

/* Show addon management buttons without opening popup */
```

> 
> And that `@namespace` line should definitely not be used in userContent.css - it's also probably a good idea to **not have it** in userChrome.css either - but that is not the issue here.

I was told several times this line must be put there when you create userChrome.css.
Actually what is it for, and why is it better not to have it?
Thank you.

**Comment by MrOtherGuy** [comment]
> I think it might be a good idea to state clearly in the page.

The readme of the repository mentions this and the files are separated on chrome and content folders accordingly. I don't know how to make it more clear without having to note the "target" file in every file - which I don't want to do.

> BTW line 4 and 6 in the page are duplicate:

Indeed there is. I'll fix that.

> I was told several times this line must be put there when you create userChrome.css.

I think that this "advice" originates from way back when there wasn't separate userChrome.css and userContent.css files. Then all the old examples around the web just happened to have a notice like "first line must be this blah blah blah" and it sort of became a myth that you need that.

Which gets to this:

> Actually what is it for, and why is it better not to have it?

Thing is, you never needed it. Maybe it *was* a good thing to have at some point but nowadays it creates you more trouble than it's worth.

What it does is it limits the contents of the file to only xul elements. This may be a bit advanced topic, but most elements in Firefox UI are xul elements. However, more and more xul elements are being replaced with html elements so if you have that xul namespace line then your css selectors won't match any html elements (meaning you can't style them)

That's the gist of it. Of course, I'm skipping loads of detail here and I don't mean to say that it should *always* be removed since there are valid uses for it. But anyone who claims that "it must be there" really has no clue what it does.

I'm closing this issue but feel free to ask further questions.

**Comment by ReporterX** [comment]
> 
> 
> The readme of the repository mentions this and the files are separated on chrome and content folders accordingly. I don't know how to make it more clear without having to note the "target" file in every file - which I don't want to do.

I see. Someone pointed me to the link directly. I didn't realise the existence of the readme. My bad.

Thanks so much for your explanation. :-)
