### ISSUE TITLE
Slight issue with autohide_sidebar.css and switcher popup

### ISSUE THREAD

**Issue by Cade66** [MrOtherGuy/firefox-csshacks#65]
Hi,

_autohide_sidebar.css_ is fantastic! I've set `--uc-sidebar-width: 0px;` to have it totally hidden and yet it opens when hovering the browser's edge: fantastic. EDIT : it works in these conditions with Firefox maximized (default here), otherwise I'd have to set it to a least 1px I guess.

I encounter a slight issue with the popup that appears when aiming to switch to another Sidebar content (Bookmarks, History etc..): as soon as I move the mouse's pointer within the popup the Sidebar hides, as if I was hovering out of the Sidebar itself. The popup remains though it's only that the sidebar gets hidden. Any way to fix that? I've tried a few little things but unsuccessfully, I'm not a coder!

Great CSS among many other great ones. I've discovered your work here when reading FirefoxCSS on reddit. You've got a basket of gems!

Thanks.

**Comment by MrOtherGuy** [comment]
You're welcome, I'm glad you found something useful.

But this issue is impossible to fix with CSS unfortunately.

While looking into it, I found that the sidebar covers statuspanel when hovered - not surprising, but I just had not thought about it. So I fixed *that* by moving statuspanel to the other side when sidebar is hovered.

I'm closing this issue as there is nothing I can do about it at current time.
