### ISSUE TITLE
Two wonky behaviours I encounter with autohide_toolbox.css

### ISSUE THREAD

**Issue by Jacosci** [MrOtherGuy/firefox-csshacks#68]
Using Firefox from portableapps.com on Windows 10 x64. I encounter two wonky behaviours:
1. Bookmark folders and overflow on bookmark bar often behaves erratically when I hover my cursor over them. Makes it pretty difficult to click an item inside them. However single items which are not inside a folder or overflow seems behaves normally.
2. When FF window isn't maximized, it's pretty hard to make the toolbox appear by mouse hover. CTRL+L works as workaround but I see noticeable delay before the toolbox pops.

Steps I've taken to try to troubleshoot:

- [x] Removing all others my CSS customization and only using autohide_toolbox.css
- [x] Disabling all extensions

I virtually have 0 knowledge about CSS. So I'd appreciate any kind of help I could get.
Here I attached my whole CSS configs just in case.
[userChrome.css.txt](https://github.com/MrOtherGuy/firefox-csshacks/files/5017084/userChrome.css.txt)
[userContent.css.txt](https://github.com/MrOtherGuy/firefox-csshacks/files/5017085/userContent.css.txt)

**Comment by MrOtherGuy** [comment]
I can't see anything wrong with folder in bookmark bar - as far as I can tell they behave exactly as you would expect them to - and so does the bookmark overflow-menu. A screen recording would help to figure out what's wrong.

The size of the are in non-maximized windows can be made bigger by decreasing the angle in line 55 - you could for instance test how 75deg works for you instead of the default 86deg.

The long delay when focused using Ctrl-L or other hotkey is a mistake on my part though - oops - but it should be fixed now.

**Comment by Jacosci** [comment]
Thanks for the response!
I've just tested the updated autohide_toolbox.css and followed your suggestion by changing the line 55 to 75deg.
Not sure if it's related to my 1st problem but it seems to have fixed the bookmark folders pop out behaviour.
You can close this issue since your suggested tweak seems working for me.
I've decided to switch to autohide_bookmarks_and_main_toolbars.css because I feel it suits better for me in terms of usability.
