### ISSUE TITLE
add-on detail page remember the scroll position

### ISSUE THREAD

**Issue by sethazazel** [MrOtherGuy/firefox-csshacks#8]
when i try to open addon detail page scroll position stay same as addons list page.like click last addon and detail page starts from bottom, click first addon detail page starts from top. (sorry for my bad english)

**Comment by MrOtherGuy** [comment]
What style causes this? Only I could think of is two_column_addons.css but I seem to be unable to reproduce the issue you described (with 8 extensions)

At any rate, I probably cannot fix this problem even if it is indeed caused by one of the stylesheets in this repository. But I would be interested in knowing what causes that behavior regardless.

**Comment by sethazazel** [comment]
yes, two_column_addons.css causes it. its not big problem for me just a little bit annoying. at first I thought css broke the detail page, then i saw scroll box were at the bottom. (i have 32 extensions)

**Comment by MrOtherGuy** [comment]
Turns out I was able to reproduce and fix this anyhow. Well, by fixing it I mean get rid of the symptom but I'm not really sure why the issue happens in the first place. I tried with 14-22 extensions and it doesn't seem to appear anymore but I can't be certain that it works for arbitrary number of addons.

**Comment by sethazazel** [comment]
latest code fixed it for me too, thank you for your attention.
