### ISSUE TITLE
dark_settings_pages.css - about:config

### ISSUE THREAD

**Issue by GrosBourrin** [MrOtherGuy/firefox-csshacks#9]
about:config part doesn't work for me, FF 66.0.3 x64 windows 10 version

**Comment by MrOtherGuy** [comment]
The code only affects the new about:config. The about:config is going to change in 67 I think to new version and it sgould work there.

In 68 though, userContent.css will not be loaded by the main process so that file will stop working then.

 However, Mozilla is adding built in support for dark settings pages (most work in current Nightlies) so this file is going to be obsolete anyway soon.

**Comment by GrosBourrin** [comment]
ok i u have understood now ! the question is "when will they stop to change continuously things  that are not really important ?" they better concentrate on stability, lightening some parts of page loading to make it faster ! btw thanks for your answer :)
