### ISSUE TITLE
Feature request: Consistent toolbar buttons

### ISSUE THREAD

**Issue by sealvessel** [MrOtherGuy/firefox-csshacks#90]
Could you make another version of consistent toolbar buttons, but by making each toolbar button having a greyscale icon as well as a border sort of like a square consistent toolbar?
![image](https://user-images.githubusercontent.com/66351949/109188837-4df80400-77ce-11eb-9f23-8e154e4a52f2.png)

**Comment by MrOtherGuy** [comment]
So basically you would want a style that makes buttons in the toolbar look like in your screenshot, correct?

I think I could make something that does something like that but I eould do it such that it makes buttons have similar aopearance to the unfocused urlbar, so that buttons hace the same border color and same background wgich will follow the colors of the selected theme.

**Comment by sealvessel** [comment]
It is sort of like the firefox-safari-style branch 0.1 buttons, except that it leaves the overall layout untouched, only affecting the icon border, margin, and padding spacing as well as making the icons tinier and greyscale.
![image](https://user-images.githubusercontent.com/66351949/109287116-251f4f80-785e-11eb-9365-ac3094aba71b.png)

**Comment by MrOtherGuy** [comment]
Right, I have created a [new file here](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/buttonlike_toolbarbuttons.css) that makes buttons look something like in your image. It should follow urlbar colors defined in whatever theme you are using (for better and for worse).
