### ISSUE TITLE
Title in menubar issue

### ISSUE THREAD

**Issue by GrosBourrin** [MrOtherGuy/firefox-csshacks#94]
hi there, i use this trick since a long time ago but couldn't resolve an issue when the window is not maximized. 
the text is outside the menubar when the window is shrinked
See pic 
![2021-03-12_04h03_02](https://user-images.githubusercontent.com/40931468/110886035-3b122300-82e8-11eb-82b2-d89351d42cd4.png)

No, i'm not on Apple system but win10, FF 86.0.1
i have added some fonts deco
i have a 1920 * 1080 screen

the title is nicely aligned when maximized

![2021-03-12_04h07_51](https://user-images.githubusercontent.com/40931468/110886183-89bfbd00-82e8-11eb-8e8a-2d70aa5e4434.png)

**Comment by MrOtherGuy** [comment]
You referring to show_window_title_in_menubar.css, and the fact that in your screenshots the title appears to be lower in non-maximized windows, correct?

Unfortunately I can't reproduce that issue. Could it be caused by other changes you appear to be making in the menubar area since the alignment of zoom/clipboard buttons is very different than normal. Yours looks better than normal for sure, but that's not what the stylesheet in question is about.

I can actually see one issue, the title appears to be 1px lower in **maximized** mode when compared to menubar text. But that is pretty hard to actually see without measuring.

**Comment by GrosBourrin** [comment]
you pointed the issue correctly . After thinking of the problem, i must see if the icons before the title are conflicting the title... 
here is my css : [https://github.com/GrosBourrin/FIREFOX-BLUE-MOON/blob/master/userChrome.css](url)
Zoom tricks are starting  line 2951 and title part at line 4435

**Comment by MrOtherGuy** [comment]
I see...

Your best option might be to just modify padding-top of `head>title` until it fits with the rest of your setup. I won't be able to make the style fit that setup "automatically".

**Comment by GrosBourrin** [comment]
i have set it to 2px and wow it works ! you're the boss ! thanks ! just to say, i stay in touch with your tricks, they're a source of inspiration. thanks again for your help, it's fixed
