### ISSUE TITLE
white line bug - autohide_toolbox.css

### ISSUE THREAD

**Issue by eim3** [MrOtherGuy/firefox-csshacks#97]
I've been using the autohide_toolbox.css for a while now and it's always worked perfectly, until sometime last week. I think since the release of FF beta v88?

Now whenever the toolbox is hidden there is a 1px of horizontal white line appearing at the top of the screen. It appears on every page and is fixed in place even when you're scrolling down a page. I don't know if you troubleshoot with beta releases but I was hoping you could look into it. Thanks!

**Comment by MrOtherGuy** [comment]
Thanks for reporting. I modified that style a bit so that it appears to work on my system. But unfortunately it's pretty annoying to test since it relies on pixel-perfect sizing of certain elements so I'm not 100% sure how that will behave.

So, please report back on how it works. And it would be extra nice if you could test how different OS scaling behavies. I tested 100%, 125% and 150% and as far as I can tell there doesn't seem to be an issue but I could have easily missed some things.

**Comment by eim3** [comment]
Sorry, I forgot to respond.

Yes, I've tested 100%, 125%, and 150% scaling as well and it seems to work fine. I'm on Win10 20H2. I don't have any other systems to test on, so I can't help you there. But thank you for the fix!

**Comment by MrOtherGuy** [comment]
Thanks a lot for confirming! 

I'll close this issue then, but feel free to re-open it if you run into some issues.

**Comment by Neuromancer233** [comment]
Hi,
Setting top margin to 8px(from 9) for the first root rule and the margin to 0px (from -1px)  removes the white line using 100% scaling on 1080p win10. 
I think setting top margin to 0px for toolbox is supposed to create other issues, but haven't felt any difference.
